force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <label>Course Product Line</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <formula>IF( 
 NOT(ISBLANK(Order_Product__c)),
 Order_Product__r.Product2.ProductCode,
 IF(
  NOT(ISBLANK(Service_Appointment__c)),
  Service_Appointment__r.Product__r.ProductCode,
  &apos;&apos;
 )
)</formula>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Sets the Category based on the Product Family, Delivery Method and other variables. Used for reporting against goals.</description>
    <formula>IF(CONTAINS(PricebookEntry.Product2.ProductCode, &quot;FACILITATORG&quot;), &quot;Facilitator&quot;,
IF(CONTAINS(PricebookEntry.Product2.ProductCode, &quot;INHOUSEG&quot;), &quot;In-House&quot;,
IF(CONTAINS(PricebookEntry.Product2.ProductCode,&quot;3RDPARTYG&quot;), &quot;Third Party&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(PricebookEntry.Product2.Delivery_Method__c,&quot;Classroom&quot;) &amp;&amp; ISPICKVAL(Classroom_Course__r.IH3POS__c, &quot;In-House&quot;), &quot;In-House&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(PricebookEntry.Product2.Delivery_Method__c,&quot;Classroom&quot;) &amp;&amp; ISPICKVAL(Classroom_Course__r.IH3POS__c, &quot;3rd Party&quot;), &quot;Third Party&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Courses&quot;) &amp;&amp;  SBQQ__RequiredBy__r.Product_Code__c = &apos;OL-JHSCI&apos;, &quot;In-House&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(PricebookEntry.Product2.Delivery_Method__c,&quot;On-site&quot;), &quot;Onsite&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Consulting Services&quot;), &quot;Consulting/Contract&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(PricebookEntry.Product2.Delivery_Method__c,&quot;Online&quot;), &quot;Online&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Memberships&quot;) &amp;&amp; ISPICKVAL(PricebookEntry.Product2.Delivery_Method__c,&quot;Online&quot;), &quot;Online Membership&quot;,
IF(ISPICKVAL(PricebookEntry.Product2.Family, &quot;Physical Goods&quot;), &quot;Materials/Videos&quot;,
null)))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Ordered Seats</relationshipLabel>
    <relationshipName>Classroom_Ordered_Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Captures the Product&apos;s Product Code.</description>
    <inlineHelpText>Indicates the Product&apos;s Product Code.</inlineHelpText>
    <label>Product Code 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the Product&apos;s Family.</description>
    <inlineHelpText>Indicates the Product&apos;s Family.</inlineHelpText>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
            <value>
                <fullName>JHSCI</fullName>
            </value>
            <value>
                <fullName>TTAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Deliver_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Sets the Category based on the Product Family, Delivery Method and other variables. Used for reporting</description>
    <formula>IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(SBQQ__Product__r.Delivery_Method__c,&quot;Classroom&quot;) &amp;&amp; ISPICKVAL(Classroom_Course__r.IH3POS__c, &quot;In-House&quot;), &quot;In-House&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(SBQQ__Product__r.Delivery_Method__c,&quot;Classroom&quot;) &amp;&amp; ISPICKVAL(Classroom_Course__r.IH3POS__c, &quot;3rd Party&quot;), &quot;Third Party&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(SBQQ__Product__r.Delivery_Method__c,&quot;On-site&quot;), &quot;Onsite&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Consulting Services&quot;), &quot;Consulting/Contract&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Courses&quot;) &amp;&amp; ISPICKVAL(SBQQ__Product__r.Delivery_Method__c,&quot;Online&quot;), &quot;Online&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Memberships&quot;) &amp;&amp; ISPICKVAL(SBQQ__Product__r.Delivery_Method__c,&quot;Online&quot;), &quot;Online Membership&quot;, 
IF(ISPICKVAL(SBQQ__Product__r.Family, &quot;Physical Goods&quot;), &quot;Materials/Videos&quot;, 
null)))))))</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Quoted Seats</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product. Populated via Process Rule for use with roll-ups.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable. Populated via Process Rule for use with roll-ups and Price Rules.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Captures the Product&apos;s Product Code. Used with roll-up summaries.</description>
    <inlineHelpText>Indicates the Product&apos;s Product Code. Used with roll-up summaries.</inlineHelpText>
    <label>RO Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the Product&apos;s Family. Populated via Process Rule for use with roll-ups.</description>
    <inlineHelpText>Indicates the Product&apos;s Family.</inlineHelpText>
    <label>RO Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderProductTriggerHandler.cls
/***************************************************************************
Name : OrderProductTriggerHandler
Created By : Aditya Chasta
Created Date : 06/14/2017
Description : Handler class for OrderProductTrigger
***************************************************************************/
public with sharing class OrderProductTriggerHandler extends TriggerHandler{
    public static List<String> productCodeExceptions = new List<String>{'TTAL', 'JHSCI'};	//product codes that are exceptions to the standard queryies
	public static Set<String> productCodeExceptionsSet = new Set<String>{'TTAL', 'JHSCI'};
    
    public override void beforeInsert() {
        System.debug('OrderProductTriggerHandler::SOQL Use (Start beforeInsert): ' + Limits.getQueries());
        Set<Id> quoteLineIdsSet = new Set<Id>();
        
        for(OrderItem oi : (List<OrderItem>) Trigger.New){
            if(oi.SBQQ__QuoteLine__c != null && (oi.Delivery_Method__c == 'Classroom' || productCodeExceptionsSet.contains(oi.Course_Product_Line__c)) && oi.Classroom_Course__c == NULL) {
                quoteLineIdsSet.add(oi.SBQQ__QuoteLine__c);
            }
        }
        
        if(quoteLineIdsSet.size() > 0){
            OrderProductTriggerHandler.populateClassroom(quoteLineIdsSet);   
        }        

		System.debug('OrderProductTriggerHandler::SOQL Use (End beforeInsert): ' + Limits.getQueries());
    }
    

    public override void afterInsert() {
        System.debug('OrderProductTriggerHandler::SOQL Use (Start afterInsert): ' + Limits.getQueries());
		List<OrderItem> updateOrderItems = new List<OrderItem>();
		List<OrderItem> deliverOrderItems = new List<OrderItem>();
		Set<Id> deliverOrderItemsId = new Set<Id>();
        Set<Id> attendeeOrderItemLink = new Set<Id>(); 
        Map<Id, Id> quoteLineOrderProductMap = new Map<Id, Id>();
        Map<Id, Id> quoteLineServiceAppointmentMap = new Map<Id, Id>();
        
        for(OrderItem oi : (List<OrderItem>) Trigger.New){
			//Deliver any order products that are to be delivered once created
            Product2 prod = [Select Id, Deliver_Immediately__c from Product2 where id = :oi.Product2Id];
            if(prod.Deliver_Immediately__c == TRUE){
                deliverOrderItemsId.add(oi.Id);
            }
            
            if(oi.Course_Product_Line__c != 'AE' && oi.SBQQ__QuoteLine__c != null && (oi.Product_Family__c == 'Courses' || oi.Category__c == 'Onsite' || (oi.Category__c == 'Online' && productCodeExceptionsSet.contains(oi.Course_Product_Line__c)))){
                //attendeeOrderItemLink.add(oi.Id);
                System.debug('AfterInsert::MAP');
                quoteLineOrderProductMap.put(oi.SBQQ__QuoteLine__c, oi.Id);
                quoteLineServiceAppointmentMap.put(oi.SBQQ__QuoteLine__c, oi.Classroom_Course__c);
            }            
        }
        
        /*
        if(attendeeOrderItemLink.size() > 0){
            OrderProductTriggerHandler.linkAttendeeOrderItems(attendeeOrderItemLink);
            OrderProductTriggerHandler.linkAttendeeClassroom(attendeeOrderItemLink);
        }
        */
        
        if(quoteLineOrderProductMap.size() > 0){
            OrderProductTriggerHandler.linkAttendeeOrderItems(quoteLineOrderProductMap);
            OrderProductTriggerHandler.linkAttendeeClassroom(quoteLineServiceAppointmentMap);
        }
        
        if(deliverOrderItemsId.size() > 0){
            for(OrderItem oi : [Select SBQQ__Status__c, Delivery_Date__c from OrderItem where id in: deliverOrderItemsId]){
                deliverOrderItems.add(oi);
            }
            BillingHelper.deliverOrderProducts(deliverOrderItems);
        }     
    }
    
    public override void afterUpdate(){
        System.debug('OrderProductTriggerHandler::SOQL Use (Start afterUpdate): ' + Limits.getQueries());
        Set<Id> attendeeOrderItemLink = new Set<Id>(); 
        Map<Id, Id> quoteLineOrderProductMap = new Map<Id, Id>();

        /*
        for(OrderItem oi : (List<OrderItem>) Trigger.New){
            if(oi.Product_Code__c == 'DLIH-JHSCII' && oi.SBQQ__RequiredBy__c != null && oi.SBQQ__QuoteLine__c != null){
                System.debug('AfterUpdate::MAP');
                quoteLineOrderProductMap.put(oi.SBQQ__QuoteLine__c, oi.Id);
            }
        }
        */
        
        /*
        if(attendeeOrderItemLink.size() > 0){
            OrderProductTriggerHandler.linkAttendeeOrderItems(attendeeOrderItemLink);
        }
        */

        if(quoteLineOrderProductMap.size() > 0){
            OrderProductTriggerHandler.linkAttendeeOrderItems(quoteLineOrderProductMap);
        }

        System.debug('OrderProductTriggerHandler::SOQL Use (End afterUpdate): ' + Limits.getQueries());
    }
    
    //Link Attendee with order product
    @future
    public static void linkAttendeeOrderItems(Set<Id> oiIds){
        List<Attendee__c> updatedAttendees = new List<Attendee__c>();
        for(OrderItem oi : [Select SBQQ__QuoteLine__c from OrderItem where id in: oiIds]){
            for(Attendee__c attendee : [Select Order_Product__c from Attendee__c where Quote_Line__c = :oi.SBQQ__QuoteLine__c]){
                attendee.Order_Product__c = oi.Id;
                updatedAttendees.add(attendee);
            }
        }
        
        if(updatedAttendees.size() > 0){
            update updatedAttendees;
        }
    }

    @future
    public static void linkAttendeeOrderItems(Map<Id, Id> quoteLineOrderProductMap){
        List<Attendee__c> updatedAttendees = new List<Attendee__c>();
        Set<Id> quoteLineIds = new Set<Id>();
        for(Id key : quoteLineOrderProductMap.keySet()){
            quoteLineIds.add(key);
        }

        List<Attendee__c> attendees = [Select Id, Quote_Line__c, Order_Product__c from Attendee__c where Quote_Line__c in :quoteLineIds];
        for(Attendee__c attendee : attendees){
            attendee.Order_Product__c = quoteLineOrderProductMap.get(attendee.Quote_Line__c);
            updatedAttendees.add(attendee);
        }

        if(updatedAttendees.size() > 0){
            update updatedAttendees;
        }
    }
    
    public static void linkAttendeeClassroom(Set<Id> oiIds){
        List<Attendee__c> updatedAttendees = new List<Attendee__c>();
        for(OrderItem oi : [Select SBQQ__QuoteLine__c, Classroom_Course__c from OrderItem where SBQQ__QuoteLine__c != null and Course_Product_Line__c in :productCodeExceptions and id in: oiIds]){
            for(Attendee__c attendee : [Select Service_Appointment__c from Attendee__c where Quote_Line__c = :oi.SBQQ__QuoteLine__c]){
                attendee.Service_Appointment__c = oi.Classroom_Course__c;
                updatedAttendees.add(attendee);
            }
        }
        
        if(updatedAttendees.size() > 0){
            update updatedAttendees;
        }
    }

    public static void linkAttendeeClassroom(Map<Id, Id> quoteLineServiceAppointmentMap){
        List<Attendee__c> updatedAttendees = new List<Attendee__c>();
        set<Id> quoteLineIds = new Set<Id>();
        for(Id key : quoteLineServiceAppointmentMap.keySet()){
            quoteLineIds.add(key);
        }

        List<Attendee__c> attendees = [Select Id, Quote_Line__c, Service_Appointment__c from Attendee__c where Quote_Line__c in :quoteLineIds];
        for(Attendee__c attendee : attendees){
            attendee.Service_Appointment__c = quoteLineServiceAppointmentMap.get(attendee.Quote_Line__c);
            updatedAttendees.add(attendee);
        }

        if(updatedAttendees.size() > 0){
            update updatedAttendees;
        }
    }
    
	public static void populateClassroom(set<Id> qlIds){
        System.debug('OrderProductTriggerHandler::SOQL Use (Start populateClassroom): ' + Limits.getQueries());
        Map<Id,Id> mapQLClassroomIds = new Map<Id, Id>();
        for(SBQQ__QuoteLine__c ql : [Select Id, Classroom_Course__c From SBQQ__QuoteLine__c Where Id IN : qlIds AND Classroom_Course__c!= null]){
            mapQLClassroomIds.put(ql.Id, ql.Classroom_Course__c);
        }
        
        if(mapQLClassroomIds.keyset().size() > 0){
            for(OrderItem item : (List<OrderItem>) Trigger.New){
                if(mapQLClassroomIds.containsKey(item.SBQQ__QuoteLine__c))
                    item.Classroom_Course__c = mapQLClassroomIds.get(item.SBQQ__QuoteLine__c);
            }
        }
        System.debug('OrderProductTriggerHandler::SOQL Use (End populateClassroom): ' + Limits.getQueries());        
    }    
    
    
    public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
            CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
    }
    
}