force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Connects to existing Contact record.</description>
    <inlineHelpText>Connects to existing Contact record.</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Quote_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects to Order Product record once Quote Line is booked.</description>
    <inlineHelpText>Connects to Order Product record once Quote Line is booked.</inlineHelpText>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects to applicable Service Appointment record.</description>
    <inlineHelpText>Connects to applicable Service Appointment record.</inlineHelpText>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Source Quote</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Days_to_Fulfill_Order__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Fulfill_Order__c</fullName>
    <defaultValue>&quot;1-2 business days&quot;</defaultValue>
    <description>Captures number of business days required to fulfill the physical goods ordered. Default = 1-2 business days.</description>
    <inlineHelpText>Indicates number of business days required to fulfill the physical goods ordered. Default = 1-2 business days.</inlineHelpText>
    <label>Days to Fulfill Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
    <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Number indicating this line&apos;s position within its group or quote.</description>
    <inlineHelpText>Number indicating this line&apos;s position within its group or quote.</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SubscriptionBase__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionBase__c</fullName>
    <description>Determines the price that serves as the base for percent-of-total calculations.</description>
    <inlineHelpText>Determines whether Percent of Total is calculated off List or Net product prices.</inlineHelpText>
    <label>Percent of Total Base</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SubscriptionScope__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionScope__c</fullName>
    <description>Determines how percent of total product prices are calculated. If scope is set to &quot;Quote&quot; any non-subscription and include in percent of total product is used in calculating every percent of total price. If scope is set to &quot;Group&quot; only products in the same group as the percent of total product are used in calculation.</description>
    <inlineHelpText>Indicates how percent of total prices are calculated: Quote uses all the non-subscription and include in percent of total products in the quote while Group uses only non-subscription products and include in percent of total products in the same group.</inlineHelpText>
    <label>Percent of Total Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term for the subscription product in this line. If the product is not a subscription this value has no effect.</description>
    <inlineHelpText>Term for this subscription. If this product is not a subscription this value has no effect.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Service Appointment to the Order Product. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</description>
    <inlineHelpText>Connects the Service Appointment to the Order Product. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</inlineHelpText>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger_Setup__c/Trigger_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Allows for activation and deactivation of Apex Triggers.</description>
    <label>Trigger Setup</label>
</CustomObject>

force-app/main/default/classes/AttendeeTriggerHandlerTest.cls
@isTest
private class AttendeeTriggerHandlerTest {

    private static void testData(){
       Trigger_Setup__c setting = (Trigger_Setup__c) SmartFactory.createSObject('Trigger_Setup__c',new Map<String, Object>{'Name' => 'Trigger Setup'});
        insert setting;
        
        Account acc = (Account) SmartFactory.createSObject('Account');
        insert acc;
        
        PermissionSetAssignment psa = [select Id, Assignee.Name, PermissionSet.Name from PermissionSetAssignment Where PermissionSet.Name = 'FSL_Resource_License' Limit 1];
        System.assertEquals(true, psa.Id != null);
        
        User u = [Select id, Email from User where Name =: psa.Assignee.Name Limit 1];
        System.assertEquals(true, u.Id != null);
        
        Contact c = (Contact)SmartFactory.createSObject('Contact', new Map<String, String>{'LastName' =>'LastName','FirstName' =>'FastName', 'AccountId' =>acc.id });
        insert c;
        
        Pricebook2 pb = (Pricebook2)SmartFactory.createSObject('Pricebook2');
        pb.IsActive=TRUE;
        insert pb;
        System.debug('Pricebook2::::'+pb);
        
        Product2 pro = (Product2)SmartFactory.createSObject('Product2');
        pro.IsActive=true;
        insert pro;
        System.debug('Product2::::'+pro);
        
        PricebookEntry stdpbe = (PricebookEntry)SmartFactory.createSObject('PricebookEntry',new Map<String, Object>{'Pricebook2Id' => Test.getStandardPricebookId(), 'Product2Id' => pro.Id});
        stdpbe.IsActive=TRUE;
        insert stdpbe;
        System.debug('STd PricebookEntry::::'+stdpbe);
        
        PricebookEntry pbe = (PricebookEntry)SmartFactory.createSObject('PricebookEntry', new Map<String, Object>{'Pricebook2Id' =>pb.Id, 'Product2Id' => pro.Id});
        pbe.IsActive=true;
        insert pbe;
        System.debug('PricebookEntry::::'+pbe);
        
        Opportunity opp = (Opportunity)SmartFactory.createSObject('Opportunity', new Map<String, String>{'Name' =>'Test Opportunity','StageName' =>'Open','AccountId' => acc.Id , 'Pricebook2Id' => pb.id}); 
        //system.assert(false,opp);
        insert opp;
        
        SBQQ__Quote__c q =  (SBQQ__Quote__c)SmartFactory.createSObject('SBQQ__Quote__c', new Map<String, Object>{'SBQQ__PrimaryContact__c' =>c.id , 'SBQQ__Opportunity__c' => opp.id, 'SBQQ__Primary__c' => true,'SBQQ__Status__c' => 'Draft','SBQQ__SubscriptionTerm__c' => 365,'SBQQ__Type__c' => 'Quote','SBQQ__StartDate__c' => Date.today()});
        insert q;
        System.debug('SBQQ__Quote__c::::'+q);
        
        SBQQ__QuoteLine__c ql = (SBQQ__QuoteLine__c)SmartFactory.createSObject('SBQQ__QuoteLine__c', new Map<String, Object>{'SBQQ__Product__c' =>pro.id,'SBQQ__Quote__c' => q.id,'SBQQ__ListPrice__c' => 10.0,'SBQQ__Quantity__c' => 10, 'SBQQ__Number__c' =>1,'Days_to_Fulfill_Order__c' =>'1-2 business days','SBQQ__SubscriptionBase__c' => 'List','SBQQ__SubscriptionScope__c'=> 'Quote'});
        insert ql;
        
        OperatingHours hour = (OperatingHours) SmartFactory.createSObject('OperatingHours');
        insert hour;
        
        WorkType wt = (WorkType) SmartFactory.createSObject('WorkType');
        insert wt;
        
        Order ord = (Order) SmartFactory.createSObject('Order',new Map<String,Object>{'AccountId'=> acc.id,'EffectiveDate' => System.today(),'Pricebook2Id'=>pb.id});
        insert ord;
        
        OrderItem ordItem = (OrderItem) SmartFactory.createSObject('OrderItem',new Map<String,Object>{'Product2Id'  =>pro.id , 'OrderId' => ord.id,'PricebookEntryId'=> pbe.id,'UnitPrice'=>100.0});
        insert ordItem;
        
        ServiceTerritory st = (ServiceTerritory)SmartFactory.createSObject('ServiceTerritory',new Map<String, Object>{'OperatingHoursId' => hour.Id,'IsActive' => true});
        insert st;
      
        WorkOrder wo = (WorkOrder)SmartFactory.createSObject('WorkOrder',new Map<String, Object>{'AccountId' => acc.id ,'ServiceTerritoryId' => st.id,'WorkTypeId'=> wt.id});
        insert wo;
 
       
    //system.assert(false,setting);
        ServiceAppointment sa = (ServiceAppointment)SmartFactory.createSObject('ServiceAppointment',new Map<String, Object>{'ParentRecordId' => wo.id});
        insert sa;

        Attendee__c att = (Attendee__c)SmartFactory.createSObject('Attendee__c',new Map<String,Object>{'Name' => 'Test','Service_Appointment__c' => sa.id,'Contact__c'=>c.id,'Order_Product__c' => ordItem.id});
        
        insert att; 
    }
    
    private static void updateTest(){
        test.startTest();
            Attendee__c att = [select id,name from Attendee__c];
            att.Name = 'Test Attendee';
            update att;
        test.stopTest();
    }
    
    private static void deleteTest(){
        test.startTest();
            Attendee__c att = [select id,name from Attendee__c];
            delete att;
            Attendee__c att2 = [select id,name from Attendee__c where id =:att.id ALL ROWS];
            undelete att2;
        test.stopTest();
    }
    
    @isTest
    static void doTestCodeCoverage(){
        AttendeeTriggerHandler.TestCodeCoverage();
    }
}