force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Connects to existing Contact record.</description>
    <inlineHelpText>Connects to existing Contact record.</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Quote_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects to Quote Line record that originated the attendees.</description>
    <inlineHelpText>Connects to Quote Line record that originated the attendees.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Source Quote</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the primary contact for &quot;on-site&quot; Quote Line, if different than Quotes.</description>
    <inlineHelpText>Indicates the primary contact for &quot;on-site&quot; Quote Line, if different than Quotes.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Scheduled_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_and_Time__c</fullName>
    <description>Captures the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</description>
    <inlineHelpText>Indicates the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</inlineHelpText>
    <label>Scheduled Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Training_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Location_Name__c</fullName>
    <description>Name of the Training address for this quote line. Pulled from Quote for On-Site/Consulting or Service Appointment for Classroom/Evaluations.</description>
    <inlineHelpText>Name of the Training address for this quote line.</inlineHelpText>
    <label>Training Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AttendeeMangementCmpApexClass.cls
/**********************************************************************
Name: AttendeeMangementCmpApexClass
Author : Shiva Sharma
Description : Lightning Component Controller for AttendeeMangement Component on Quote Object
**********************************************************************/

public class AttendeeMangementCmpApexClass {

    //Getting related Attendee linked to Quote through QuoteLines
    @AuraEnabled
    public static List<Attendee__c> getAttLst(Id RecordId){//Parameter RecordId <==> Quote__r.Id
        List<Attendee__c> attendeeList ;
        try{
            attendeeList = [select id,name,Quote_Line__r.name,Quote_Line__r.Training_Location_Name__c,Quote_Line__r.Scheduled_Date_and_Time__c,Quote_Line__r.SBQQ__Product__r.Name,contact__c from Attendee__c where Quote_Line__r.SBQQ__Quote__c=:RecordId and Quote_Line__r.SBQQ__RequiredBy__c = null order by Quote_Line__r.Name];
        }catch(Exception e){
             System.debug('Error: '+e.getMessage()+e.getStackTraceString()); 
        }
        return attendeeList;
        
    }

    @AuraEnabled
    public static List<Contact> getContactsByString(Id accId, String searchQuery, String ignoreContactId){
        try {
            String queryName = '%'+ String.escapeSingleQuotes(searchQuery) + '%';
            List<Contact> contacts = [Select Id, Name, FirstName, LastName, Email from Contact where Id != :ignoreContactId and AccountId =:accId and Name like :queryName order by FirstName limit 15];
            return contacts;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Update attendee from AttendeeMangement Component
    @AuraEnabled
    public static Boolean reviseAttendee(Id attendeeId, Id newContactId){
        try {
                Attendee__c attendee = new Attendee__c(
                Id = attendeeId,
                Contact__c = newContactId
            );
            update attendee;
               
           //Check each attendees quote line for related quote line to populate attendee               

             Attendee__c attd = [Select Id, Quote_Line__c from Attendee__c where Id =: attendeeId][0];
             SBQQ__QuoteLine__c ql = [Select Id, (Select Id from SBQQ__Quote_Lines__r) from SBQQ__QuoteLine__c where id =: attd.Quote_Line__c];
             for(SBQQ__QuoteLine__c quoteLine : ql.SBQQ__Quote_Lines__r){
                 List<Attendee__c> dl2Attendees = [Select Id, Contact__c, Name from Attendee__c where Quote_Line__c =: quoteLine.Id];
                 for(Attendee__c dl2Attendee : dl2Attendees){
                        dl2Attendee.Contact__c = newContactId;
                 }
                 update dl2Attendees;
             }
          return true;
          //check for any child quote lines to populate those attendees as well (JHSC Bundle)
        } 
        catch (Exception e) {
            System.debug('Error: '+e.getMessage()+e.getStackTraceString()); 
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Update attendee from AttendeeMangement Component
    @AuraEnabled
    public static String UpdateAttendee(List<Attendee__c> AttendeeList){//List of Updated attendee Records
        List<Attendee__c> attendees = new List<Attendee__c>();//New List to Map old with New List
        System.debug('Before is');
        System.debug(attendees);
        try{
           for(Attendee__c attnd : AttendeeList){
               //Add new Attndee
               attendees.add(new Attendee__c(
                   id = attnd.id,
                   contact__c = attnd.contact__c,
                   name = attnd.name 
               ));
               System.debug('debug is');
               System.debug(attnd);
             
               //Check each attendees quote line for related quote line to populate attendee               
               Attendee__c attendee = [Select Id, Quote_Line__c from Attendee__c where Id =: attnd.Id][0];
               SBQQ__QuoteLine__c ql = [Select Id, (Select Id from SBQQ__Quote_Lines__r) from SBQQ__QuoteLine__c where id =: attendee.Quote_Line__c];
               for(SBQQ__QuoteLine__c quoteLine : ql.SBQQ__Quote_Lines__r){
                   List<Attendee__c> dl2Attendees = [Select Id, Contact__c, Name from Attendee__c where Quote_Line__c =: quoteLine.Id];
                   for(Attendee__c dl2Attendee : dl2Attendees){
                       attendees.add(new Attendee__c(
                           id = dl2Attendee.Id,
                           contact__c = attnd.Contact__c,
                           name = attnd.Name
                       ));
                   }
               }
            }
            // Update the Attendee List
            System.debug('After is');
            System.debug(attendees);
            update attendees; 
            
            //check for any child quote lines to populate those attendees as well (JHSC Bundle)
            
        }
        catch(Exception e){
             System.debug('Error: '+e.getMessage()+e.getStackTraceString()); 
             throw new AuraHandledException(e.getMessage()); 
        }
        
        return null;
    }
    
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;   
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;        
    }
}