force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>IF(ISBLANK( Contact__r.Account.ShippingAddress ), 
&apos;&apos;,
Contact__r.Account.ShippingStreet + &apos;, &apos; 
+ Contact__r.Account.ShippingCity + &apos;, &apos; 
+ Contact__r.Account.ShippingState + &apos;, &apos;
+ Contact__r.Account.ShippingPostalCode + &apos;, &apos;
+ Contact__r.Account.ShippingCountry
)</formula>
    <label>Contact&apos;s Account Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects to Order Product record once Quote Line is booked.</description>
    <inlineHelpText>Connects to Order Product record once Quote Line is booked.</inlineHelpText>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Order_Product__r.Product2.External_Product_Name__c</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects to applicable Service Appointment record.</description>
    <inlineHelpText>Connects to applicable Service Appointment record.</inlineHelpText>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/ShipStation_Do_Not_Sync__c.field-meta.xml
<CustomField>
    <fullName>ShipStation_Do_Not_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ShipStation Do Not Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to Accounts for easier visibility.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Ordered Seats</relationshipLabel>
    <relationshipName>Classroom_Ordered_Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__OrderedQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__OrderedQuantity__c</fullName>
    <description>The actual quantity of the product placed in the order.</description>
    <inlineHelpText>The actual quantity of the product placed in the order.</inlineHelpText>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to the Account. Set based on the Parent Record</description>
    <inlineHelpText>Connection to the Account. Set based on the Parent Record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Service Appointment to the Order Product. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</description>
    <inlineHelpText>Connects the Service Appointment to the Order Product. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</inlineHelpText>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</description>
    <inlineHelpText>Indicates the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Service_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource_Name__c</fullName>
    <formula>if( isblank(Text(Contractor__c)), 

 Assigned_Service_Resource__r.FirstName + &quot; &quot; +  Assigned_Service_Resource__r.LastName

, Text(Contractor__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Resource Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Spaces_Left__c.field-meta.xml
<CustomField>
    <fullName>Spaces_Left__c</fullName>
    <formula>Course_Max_Capacity__c - Confirmed_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spaces Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AttendeeTransferToolHandler.cls
public with sharing class AttendeeTransferToolHandler {
    @AuraEnabled
    public static List<ServiceAppointment> getServiceAppointments(Integer numberOfAttendees, Id productId, ID ignoreSAId){
        List<ServiceAppointment> serviceAppointments = [Select Id, AppointmentNumber, SchedStartTime, Service_Resource_Name__c from ServiceAppointment where Product__c =: productId and Status = 'Assigned' and Spaces_Left__c >=: numberOfAttendees and SchedStartTime > Today and Id != :ignoreSAId order by SchedStartTime];
        return serviceAppointments;
    }

    @AuraEnabled
    public static Integer transferAttendees(ID oldSAId, ID newSAId, Integer numberOfAttendees){
        try {
            Integer numberOfAttendeesProcessed = 0;

            List<OrderItem> orderItems = [Select Id, SBQQ__OrderedQuantity__c, Classroom_Course__c from OrderItem where Classroom_Course__c =: oldSAId and SBQQ__Status__c = 'Draft' order by SBQQ__OrderedQuantity__c desc, Account__c desc];
            List<Attendee__c> attendees = new List<Attendee__c>();

            for(OrderItem orderItem : orderItems){
                if((orderItem.SBQQ__OrderedQuantity__c + numberOfAttendeesProcessed) > numberOfAttendees){
                    continue;
                }
                else{
                    orderItem.Classroom_Course__c = newSAId;
                    for(Attendee__c attendee : [Select Id, Service_Appointment__c, ShipStation_Do_Not_Sync__c from Attendee__c where Order_Product__c =: orderItem.Id]){
                        attendee.Service_Appointment__c = newSAId;
                        attendees.add(attendee);
                        numberOfAttendeesProcessed++;
                    }
                }
            }

            update orderItems;
            update attendees;

            return numberOfAttendeesProcessed;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;        
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
	}    
}