force-app/main/default/objects/Time_Off_Request__c/Time_Off_Request__c.object-meta.xml
<CustomObject>
    <description>Captures the time-off requests from trainers for management approval. Creates a Resource Absence record once approved.</description>
    <label>Time-Off Request</label>
    <nameField>
        <displayFormat>TOF-{00000}</displayFormat>
        <label>Time-Off Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time-Off Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Off_Request__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY() + 1)&amp;&apos; 3:59:00&apos;)</defaultValue>
    <description>Captures the date/time the time-off request ends.</description>
    <inlineHelpText>Indicates the date/time the time-off request ends.</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Reason_for_Absence__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Absence__c</fullName>
    <description>Captures the reason the time-off is being requested.</description>
    <inlineHelpText>Indicates the reason the time-off is being requested.</inlineHelpText>
    <label>Reason for Absence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <description>Captures the Service Resource submitting the time-off request.</description>
    <inlineHelpText>Indicates the Service Resource  submitting the time-off request.</inlineHelpText>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Time-Off Requests</relationshipLabel>
    <relationshipName>Time_Off_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 04:00:00&apos;)</defaultValue>
    <description>Captures the date/time the time-off request beings.</description>
    <inlineHelpText>Indicates the date/time the time-off request beings.</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the status of the Time-Off Request record.</description>
    <inlineHelpText>Indicates the status of the Time-Off Request record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Time_Off_Request__c.field-meta.xml
<CustomField>
    <fullName>Time_Off_Request__c</fullName>
    <displayFormat>TOF-{00000}</displayFormat>
    <label>Time-Off Request #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Type_of_Absence_Requested__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Absence_Requested__c</fullName>
    <description>Captures the type of request being submitted.</description>
    <inlineHelpText>Indicates the type of request being submitted.</inlineHelpText>
    <label>Type of Absence Requested</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Banked</fullName>
            </value>
            <value>
                <fullName>Bereavement</fullName>
            </value>
            <value>
                <fullName>Jury</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Saved for JHSC</fullName>
            </value>
            <value>
                <fullName>4DWW</fullName>
            </value>
            <value>
                <fullName>Unscheduled Work Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TimeOffRequestTriggerHandler.cls
public with sharing class TimeOffRequestTriggerHandler extends TriggerHandler{
    public List<Time_Off_Request__c> timeOffReqs;  //List of TimeRequests
    
    public override void beforeInsert(){
        timeOffReqs = new List<Time_Off_Request__c>();
        for(Time_Off_Request__c tr : (List<Time_Off_Request__c>) Trigger.New){
            if(tr.Status__c != NULL && tr.Status__c == 'Approved') //filtring booked Quotes  
                timeOffReqs.add(tr);
        }
        if(timeOffReqs.size() > 0){
            TimeOffRequestTriggerHandler.createResorceAbsence(timeOffReqs);
        }
    }
    
    public override void beforeUpdate(){
        timeOffReqs = new List<Time_Off_Request__c>();
        for(Time_Off_Request__c tr : (List<Time_Off_Request__c>) Trigger.New){
            if(tr.Status__c != NULL && tr.Status__c == 'Approved') //filtring booked Quotes  
                timeOffReqs.add(tr);
        }
        if(timeOffReqs.size() > 0){
            TimeOffRequestTriggerHandler.createResorceAbsence(timeOffReqs);
        }
    }
    
    public Static void createResorceAbsence(List<Time_Off_Request__c> lstTimeOffReq){
    	List<ResourceAbsence> resourceAbsenceLst = new List<ResourceAbsence>();
    	Id recAbsRecTypeId = Schema.SObjectType.ResourceAbsence.RecordTypeInfosByName.get('Non Availability').RecordTypeId;
    	for(Time_Off_Request__c tr : lstTimeOffReq){
    		ResourceAbsence ra = new ResourceAbsence();
    		ra.RecordTypeId = recAbsRecTypeId;
    		ra.ResourceId = tr.Service_Resource__c;
    		ra.Start = tr.Start_Date_Time__c;
    		ra.End = tr.End_Date_Time__c;
    		ra.Type = tr.Type_of_Absence_Requested__c;
    		ra.Description = tr.Reason_for_Absence__c;
    		resourceAbsenceLst.add(ra);
    	}
    	if(resourceAbsenceLst.size() > 0){
    		insert resourceAbsenceLst;
    	}
    }
}