force-app/main/default/objects/Time_Off_Request__c/Time_Off_Request__c.object-meta.xml
<CustomObject>
    <description>Captures the time-off requests from trainers for management approval. Creates a Resource Absence record once approved.</description>
    <label>Time-Off Request</label>
    <nameField>
        <displayFormat>TOF-{00000}</displayFormat>
        <label>Time-Off Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time-Off Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Off_Request__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY() + 1)&amp;&apos; 3:59:00&apos;)</defaultValue>
    <description>Captures the date/time the time-off request ends.</description>
    <inlineHelpText>Indicates the date/time the time-off request ends.</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Reason_for_Absence__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Absence__c</fullName>
    <description>Captures the reason the time-off is being requested.</description>
    <inlineHelpText>Indicates the reason the time-off is being requested.</inlineHelpText>
    <label>Reason for Absence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <description>Captures the Service Resource submitting the time-off request.</description>
    <inlineHelpText>Indicates the Service Resource  submitting the time-off request.</inlineHelpText>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Time-Off Requests</relationshipLabel>
    <relationshipName>Time_Off_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <defaultValue>DATETIMEVALUE(TEXT(TODAY())&amp;&apos; 04:00:00&apos;)</defaultValue>
    <description>Captures the date/time the time-off request beings.</description>
    <inlineHelpText>Indicates the date/time the time-off request beings.</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the status of the Time-Off Request record.</description>
    <inlineHelpText>Indicates the status of the Time-Off Request record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Time_Off_Request__c.field-meta.xml
<CustomField>
    <fullName>Time_Off_Request__c</fullName>
    <displayFormat>TOF-{00000}</displayFormat>
    <label>Time-Off Request #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Time_Off_Request__c/fields/Type_of_Absence_Requested__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Absence_Requested__c</fullName>
    <description>Captures the type of request being submitted.</description>
    <inlineHelpText>Indicates the type of request being submitted.</inlineHelpText>
    <label>Type of Absence Requested</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Banked</fullName>
            </value>
            <value>
                <fullName>Bereavement</fullName>
            </value>
            <value>
                <fullName>Jury</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Saved for JHSC</fullName>
            </value>
            <value>
                <fullName>4DWW</fullName>
            </value>
            <value>
                <fullName>Unscheduled Work Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Setup__c/Trigger_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Allows for activation and deactivation of Apex Triggers.</description>
    <label>Trigger Setup</label>
</CustomObject>

force-app/main/default/classes/TimeOffRequestTriggerHandlerTest.cls
@isTest
private class TimeOffRequestTriggerHandlerTest {
    @testSetup
    static void testData(){
        Trigger_Setup__c setting = (Trigger_Setup__c) SmartFactory.createSObject('Trigger_Setup__c',new Map<String, Object>{'Name' => 'Trigger Setup'});
        insert setting;
        
        PermissionSetAssignment psa = [select Id, Assignee.Name, PermissionSet.Name from PermissionSetAssignment Where PermissionSet.Name = 'FSL_Resource_License' Limit 1];
        System.assertEquals(true, psa.Id != null);
        
        User u = [Select id from User where Name =: psa.Assignee.Name Limit 1];
        System.assertEquals(true, u.Id != null);
        
        OperatingHours hour = (OperatingHours) SmartFactory.createSObject('OperatingHours');
        insert hour;
        
        ServiceTerritory st = (ServiceTerritory)SmartFactory.createSObject('ServiceTerritory',new Map<String, Object>{'OperatingHoursId' => hour.Id,'IsActive' => true});
        insert st;
        
        ServiceResource sr = (ServiceResource)SmartFactory.createSObject('ServiceResource',new Map<String,Object>{'Name' => 'Test', 'External_ID__c' => 'ex1', 'IsActive' => true, 'RelatedRecordId'=>u.id});
        insert sr;
        
        ServiceTerritoryMember stm = (ServiceTerritoryMember)SmartFactory.createSObject('ServiceTerritoryMember',new Map<String,Object>{'ServiceTerritoryId'=> st.Id, 'ServiceResourceId' => sr.Id, 'TerritoryType'=>'P'});
        insert stm;
        
        Time_Off_Request__c tr = (Time_Off_Request__c)SmartFactory.createSObject('Time_Off_Request__c',new Map<String,Object>{'Service_Resource__c'=>sr.Id,'Type_of_Absence_Requested__c'=>'Sick','Start_Date_Time__c'=>system.now(),'End_Date_Time__c'=>(system.now()).addMonths(1),'Reason_for_Absence__c'=>'test','Status__c'=>'Draft'});
        insert tr;
     }
    
     static testmethod void updateTest(){
         Test.startTest();
         Time_Off_Request__c tor = [Select Id from Time_Off_Request__c];
         tor.Status__c = 'Approved';
         update tor;
         Test.stopTest();
        
       
    }
}