force-app/main/default/objects/Order/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (Primary Contact)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Source Quote</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lookup - Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Lookup - Primary Contact)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
    <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Annual_Safety_Inspection_Eval_Details__c.field-meta.xml
<CustomField>
    <fullName>Annual_Safety_Inspection_Eval_Details__c</fullName>
    <description>Captures whether the annual safety inspection has been completed on the equipment beng used for evaluation.</description>
    <inlineHelpText>Indicates whether the annual safety inspection has been completed on the equipment beng used for evaluation.</inlineHelpText>
    <label>Annual Safety Inspection Eval Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable. Populated via Process Rule for use with roll-ups and Price Rules.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Lifting_Device_Eval_Details__c.field-meta.xml
<CustomField>
    <fullName>Lifting_Device_Eval_Details__c</fullName>
    <description>Captures the type(s) and number(s) of lifting device(s) each person needs to be evaluated on.</description>
    <inlineHelpText>Indicates the type(s) and number(s) of lifting device(s) each person needs to be evaluated on.</inlineHelpText>
    <label>Lifting Device Eval Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the primary contact for &quot;on-site&quot; Quote Line, if different than Quotes.</description>
    <inlineHelpText>Indicates the primary contact for &quot;on-site&quot; Quote Line, if different than Quotes.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Annual_Safety_Inspection_Eval_Details__c.field-meta.xml
<CustomField>
    <fullName>Annual_Safety_Inspection_Eval_Details__c</fullName>
    <description>Captures whether the annual safety inspection has been completed on the equipment beng used for evaluation.</description>
    <inlineHelpText>Indicates whether the annual safety inspection has been completed on the equipment beng used for evaluation.</inlineHelpText>
    <label>Annual Safety Inspection Eval Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Lifting_Device_Eval_Details__c.field-meta.xml
<CustomField>
    <fullName>Lifting_Device_Eval_Details__c</fullName>
    <description>Captures the type(s) and number(s) of lifting device(s) each person needs to be evaluated on.</description>
    <inlineHelpText>Indicates the type(s) and number(s) of lifting device(s) each person needs to be evaluated on.</inlineHelpText>
    <label>Lifting Device Eval Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Service Appointment to the Order. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</description>
    <inlineHelpText>Connects the Service Appointment to the Order. Populated when &quot;On-Site&quot; Service Appointments are booked as part of the confirmation process.</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>Account__r.Primary_Contact__r.FullName__c</formula>
    <label>Primary Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</description>
    <inlineHelpText>Indicates the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Service Appointment to the Quote. Populated when &quot;On-Site&quot; Service Appointments are created as part of the quoting process.</description>
    <inlineHelpText>Connects the Service Appointment to the Quote. Populated when &quot;On-Site&quot; Service Appointments are created as part of the quoting process.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connects the Service Appointment to the Quote Line. Populated when &quot;On-Site&quot; Service Appointments are created as part of the quoting process.</description>
    <inlineHelpText>Connects the Service Appointment to the Quote Line. Populated when &quot;On-Site&quot; Service Appointments are created as part of the quoting process.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OnSiteCourseQuestionApexController.cls
public class OnSiteCourseQuestionApexController {

    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getCourses(Id quoteId) {
        List<SBQQ__QuoteLine__c> coursesQL = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c quoteline : [Select Id, Name,SBQQ__Quote__c,SBQQ__Quote__r.SBQQ__PrimaryContact__c,Primary_Contact__c,SBQQ__Product__r.Name,SBQQ__Product__r.Family, SBQQ__Product__r.Delivery_Method__c,Lifting_Device_Eval_Details__c,Annual_Safety_Inspection_Eval_Details__c, (Select Id,SchedStartTime, City, StateCode From Service_Appointments__r Order By lastmodifieddate desc limit 1) From SBQQ__QuoteLine__c Where SBQQ__Quote__c =: quoteId AND (SBQQ__Product__r.Family = 'Courses' OR SBQQ__Product__r.Family = 'Consulting Services') AND SBQQ__Product__r.Delivery_Method__c = 'On-site' ]){
            if(quoteLine.Primary_Contact__c == null){
                quoteLine.Primary_Contact__c = quoteline.SBQQ__Quote__r.SBQQ__PrimaryContact__c;
            }
            coursesQL.add(quoteLine);
        }
        return coursesQL;
    }
    
    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> getEvaluations(Id quoteId) {
        List<SBQQ__QuoteLine__c> evaluationsQL = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c quoteline : [Select Id, Name,SBQQ__Quote__c,SBQQ__Quote__r.SBQQ__PrimaryContact__c,Primary_Contact__c,SBQQ__Product__r.Name,SBQQ__Product__r.Family, SBQQ__Product__r.Delivery_Method__c,Lifting_Device_Eval_Details__c,Annual_Safety_Inspection_Eval_Details__c, (Select Id,SchedStartTime, City, StateCode From Service_Appointments__r Order By lastmodifieddate desc limit 1) From SBQQ__QuoteLine__c Where SBQQ__Quote__c =: quoteId AND SBQQ__Product__r.Family = 'Evaluations' AND SBQQ__Product__r.Delivery_Method__c = 'On-site']){
            if(quoteLine.Primary_Contact__c == null){
                quoteLine.Primary_Contact__c = quoteline.SBQQ__Quote__r.SBQQ__PrimaryContact__c;
            }
            evaluationsQL.add(quoteLine);
        } 
        return evaluationsQL;
    }
    
    @AuraEnabled
    public static List<SBQQ__QuoteLine__c> saveQuoteLine(List<SBQQ__QuoteLine__c> quoteLineToSave) {
        system.debug('<<<<>>>>'+quoteLineToSave);
        List<SBQQ__QuoteLine__c> lstToSave = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c ql : quoteLineToSave){
            SBQQ__QuoteLine__c qlRec = new SBQQ__QuoteLine__c(Id = ql.Id);
            if(ql.Primary_Contact__c != null){
               qlRec.Primary_Contact__c = ql.Primary_Contact__c;
            }
            else{
               qlRec.Primary_Contact__c = null;
            }
            qlRec.Lifting_Device_Eval_Details__c = ql.Lifting_Device_Eval_Details__c;
            qlRec.Annual_Safety_Inspection_Eval_Details__c = ql.Annual_Safety_Inspection_Eval_Details__c;
       
            lstToSave.add(qlRec);
        }
        System.debug('#####'+lstToSave);
        update lstToSave;
        return quoteLineToSave;
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
	}    
}