force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <label>Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Costs</relationshipLabel>
    <relationshipName>Product_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductCostTriggerHandlerTest.cls
@isTest
public class ProductCostTriggerHandlerTest {
    @isTest
    static void deployTrigger(){
        Product2 prod = (Product2) SmartFactory.createSObject('Product2');
        insert prod;         
        
        Product_Cost__c productCost = new Product_Cost__c();        
        productCost.Name = 'Test';
        productCost.Amount__c = 100.0;
        productCost.Product__c = prod.Id;
        insert productCost;
        
        productCost.Amount__c = 90.0;
        update productCost;
        
        delete productCost;
    }
    
    @isTest
    static void doTestCodeCoverage(){
        ProductCostTriggerHandler.TestCodeCoverage();
    }  
}