force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to Accounts for easier visibility.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Automated_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Automated_Billing_Date__c</fullName>
    <inlineHelpText>If the product creates recurring invoices, this field will indicate when the next invoicing date will be</inlineHelpText>
    <label>Automated Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the booked seats for a given classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Ordered Seats</relationshipLabel>
    <relationshipName>Classroom_Ordered_Seats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contracted_Discount_Display__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Discount_Display__c</fullName>
    <label>Contracted Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/External_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Product_Name__c</fullName>
    <description>Captures the external product name to be used on Order output documents. Populated upon creation of Order Product.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indicates the external product name to be used on Order output documents.</inlineHelpText>
    <label>External Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Captures the Product&apos;s Product Code.</description>
    <inlineHelpText>Indicates the Product&apos;s Product Code.</inlineHelpText>
    <label>Product Code 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the Product&apos;s Family.</description>
    <inlineHelpText>Indicates the Product&apos;s Family.</inlineHelpText>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Captures the Product&apos;s Product Name.</description>
    <inlineHelpText>Indicates the Product&apos;s Product Name.</inlineHelpText>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Promo_Discount_Amt__c.field-meta.xml
<CustomField>
    <fullName>Promo_Discount_Amt__c</fullName>
    <label>Promo Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Promotional_Discount__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Code</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax__c</fullName>
    <label>Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__OrderedQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__OrderedQuantity__c</fullName>
    <description>The actual quantity of the product placed in the order.</description>
    <inlineHelpText>The actual quantity of the product placed in the order.</inlineHelpText>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__TaxCode__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TaxCode__c</fullName>
    <description>Specifies the tax code for taxation rules.</description>
    <inlineHelpText>IGNORE. Specifies the tax code for taxation rules.</inlineHelpText>
    <label>Tax code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Scheduled_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_and_Time__c</fullName>
    <description>Captures the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</description>
    <inlineHelpText>Indicates the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</inlineHelpText>
    <label>Scheduled Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax_Province__c.field-meta.xml
<CustomField>
    <fullName>Tax_Province__c</fullName>
    <label>Tax Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Captures the Tax Rate applicable to this Order Product based on the Province.</description>
    <inlineHelpText>Indicates the Tax Rate applicable to this Order Product based on the Province.</inlineHelpText>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Amount_Without_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Without_Tax__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Net_Price__c</fullName>
    <label>Total Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>(Quantity*UnitPrice) - Promo_Discount_Amt__c  + Sales_Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Train_the_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Train_the_Trainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captures whether the course Product is delivered as Train-the-Trainer.</description>
    <inlineHelpText>Indicates whether the course Product is delivered as Train-the-Trainer.</inlineHelpText>
    <label>Train-the-Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/External_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Product_Name__c</fullName>
    <description>Captures the external product name to be used on quote output documents.</description>
    <inlineHelpText>Indicates the external product name to be used on quote output documents.</inlineHelpText>
    <label>External Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Recurring_Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Invoice_Frequency__c</fullName>
    <label>Recurring Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Recurring_Invoice_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <description>Captures the standard price displayed on the course.</description>
    <inlineHelpText>Indicates the standard price displayed on the course.</inlineHelpText>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/Tax_Rate__c.object-meta.xml
<CustomObject>
    <description>Captures the tax rates for each region. Utilized to calculate tax on the SBQQ_QuoteLine.</description>
    <label>Tax Rate</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Tax Rate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Rate__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Captures the Tax Rate for the province.</description>
    <inlineHelpText>Indicates the Tax Rate for the province.</inlineHelpText>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/RecurringBillingTool.cls
/***************************
Class Name: RecurringBillingTool
Author: Blessen Mathew
Description: Class to help with membership style billing

History Log
=====================================
2021-08-12		BMathew		Created initial class
2021-10-01		BMathew		Adjusted billing period to check product frequency to determine next invoice date
2022-06-20      BMathew     Added a check against the current product price. Add a contracted discount if difference exists
****************************/
public class RecurringBillingTool implements Schedulable{
    public void execute(SchedulableContext sc){
        generateAutomatedOrderProduct();
    }

    public static void generateAutomatedOrderProduct(){
        List<OrderItem> orderItems = [Select Id, Automated_Billing_Date__c, (Select Id from SBQQ__Components__r) from OrderItem where Automated_Billing_Date__c = TODAY and SBQQ__Status__c != 'Canceled'];
        for(OrderItem orderItem : orderItems){
            if(orderItem.SBQQ__Components__r == null || orderItem.SBQQ__Components__r.size() == 0){
                OrderItem op = [Select Account__c, SBQQ__Status__c, Product2Id, Product2.Recurring_Invoice_Frequency__c, Classroom_Course__c, Course_Product_Line__c, Delivery_Method__c, External_Product_Name__c, ListPrice, List_Unit_Price__c, Net_Unit_Price__c, Contracted_Discount_Display__c, Product2.Standard_Price__c, OrderId, SBQQ__OrderedQuantity__c, Product_Code__c, Product_Family__c, Product_Name__c, Promo_Discount_Amt__c, Promotional_Discount__c, Quantity, Scheduled_Date_and_Time__c, Total_Amount_Without_Tax__c, SBQQ__TaxCode__c, Tax_Province__c, Tax_Rate__c, Total_Price__c, Total_Net_Price__c, TotalPrice, Sales_Tax__c, Train_the_Trainer__c, Training_City__c, Training_Country__c, Training_Location_Name__c, Training_Postal_Code__c, Training_Province__c, Training_Street__c, UnitPrice, Volume_Discount__c, Wall_Certificate__c, Wallet_Card__c, Work_Type__c, PricebookEntryId, SBQQ__RequiredBy__c from OrderItem where id=:orderItem.Id];
                Order order = [Select Id, Status from Order where Id =: op.OrderId];
                
                SBQQ.TriggerControl.disable();
                order.Status = 'Draft';
                update order;
                SBQQ.TriggerControl.enable(); 
                
                OrderItem oi = op.clone(false, false, false, false);
                oi.Delivery_Date__c = system.today();
                oi.SBQQ__RequiredBy__c = op.Id;
                
                if(oi.Product2.Standard_Price__c > oi.ListPrice){
                    Decimal difference = (oi.ListPrice - oi.Product2.Standard_Price__c).round(System.RoundingMode.Down);
                    oi.ListPrice = oi.Product2.Standard_Price__c;
                    oi.List_Unit_Price__c = oi.Product2.Standard_Price__c;
                    oi.Contracted_Discount_Display__c = difference;
                    oi.UnitPrice = oi.ListPrice + difference;
                }
                
                DateTime dt = System.now();
                DateTime dtNextInvoice;
                if(op.Product2.Recurring_Invoice_Frequency__c == 'Monthly'){
                    dtNextInvoice = dt.addMonths(1);
                }
                else{
                    dtNextInvoice = dt.addMonths(12);
                }
                DateTime automatedBillingLabelDt = DateTime.newInstance(dtNextInvoice.year(), dtNextInvoice.month(), dtNextInvoice.day() - 1);
                String memo = dt.format('MMMM') + ' ' + dt.day() + ', ' + dt.year() + ' - ' + automatedBillingLabelDt.format('MMMM') + ' ' + automatedBillingLabelDt.day() + ', ' + automatedBillingLabelDt.year();
                
                oi.Invoice_Memo__c = memo;
                
                insert oi;
                
                SBQQ.TriggerControl.disable();
                order.Status = 'Activated';
                update order;
                SBQQ.TriggerControl.enable();
            }
            else{
                continue;
            }
        }
    }

    public static void testCodeCoverage(){
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
    }    
}