force-app/main/default/objects/Account/fields/April_Sales__c.field-meta.xml
<CustomField>
    <fullName>April_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>April Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/August_Sales__c.field-meta.xml
<CustomField>
    <fullName>August_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>August Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/December_Sales__c.field-meta.xml
<CustomField>
    <fullName>December_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>December Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/February_Sales__c.field-meta.xml
<CustomField>
    <fullName>February_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>February Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fiscal_Q1_Sales__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Q1_Sales__c</fullName>
    <formula>September_Sales__c + October_Sales__c + November_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Q1 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fiscal_Q2_Sales__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Q2_Sales__c</fullName>
    <formula>December_Sales__c + January_Sales__c + February_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Q2 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fiscal_Q3_Sales__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Q3_Sales__c</fullName>
    <formula>March_Sales__c + April_Sales__c + May_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Q3 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fiscal_Q4_Sales__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Q4_Sales__c</fullName>
    <formula>June_Sales__c + July_Sales__c + August_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Q4 Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fiscal_Year_Sales__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_Sales__c</fullName>
    <formula>Fiscal_Q1_Sales__c + Fiscal_Q2_Sales__c + Fiscal_Q3_Sales__c + Fiscal_Q4_Sales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Year Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/January_Sales__c.field-meta.xml
<CustomField>
    <fullName>January_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>January Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/July_Sales__c.field-meta.xml
<CustomField>
    <fullName>July_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>July Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/June_Sales__c.field-meta.xml
<CustomField>
    <fullName>June_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>June Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/March_Sales__c.field-meta.xml
<CustomField>
    <fullName>March_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>March Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/May_Sales__c.field-meta.xml
<CustomField>
    <fullName>May_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>May Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/November_Sales__c.field-meta.xml
<CustomField>
    <fullName>November_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>November Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/October_Sales__c.field-meta.xml
<CustomField>
    <fullName>October_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>October Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recalculate_Sales__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/September_Sales__c.field-meta.xml
<CustomField>
    <fullName>September_Sales__c</fullName>
    <defaultValue>0</defaultValue>
    <label>September Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to Accounts for easier visibility.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CRM_Statement_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>CRM_Statement_Item_Id__c</fullName>
    <label>CRM Statement Item Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Amount_Without_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Without_Tax__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SalesGoalDailyCalculator.cls
public class SalesGoalDailyCalculator implements Schedulable{
    public void execute(SchedulableContext sc){
        calculateDailySales();
    }

    public static void calculateDailySales(){
        List<Account> accounts = [Select Id, Fiscal_Year_Sales__c, Fiscal_Q1_Sales__c, Fiscal_Q2_Sales__c, Fiscal_Q3_Sales__c, Fiscal_Q4_Sales__c, January_Sales__c, February_Sales__c, March_Sales__c, April_Sales__c, May_Sales__c, June_Sales__c, July_Sales__c, August_Sales__c, September_Sales__c, October_Sales__c, November_Sales__c, December_Sales__c from Account where Recalculate_Sales__c = true limit 600];
        Set<Id> accountIds = new Set<Id>();
        List<Account> updateAccounts = new List<Account>();

        Integer iteration = 0;
        for(Account account : accounts){
            iteration++;
            accountIds.add(account.Id);
            
            if((accountIds.size() == 100) || ((accounts.size() - iteration) == 0)){
                List<AggregateResult> fiscalMonthlySales = [Select Account__c, sum(Total_Amount_Without_Tax__c) total_sales, CALENDAR_MONTH(CreatedDate) CM from OrderItem where Account__c in :accountIds and SBQQ__Status__c != 'Canceled' and (CRM_Statement_Item_Id__c = null or CRM_Statement_Item_Id__c = 0) and CreatedDate = THIS_MONTH group by Account__c, CALENDAR_MONTH(CreatedDate) order by CALENDAR_MONTH(CreatedDate)];
                for(AggregateResult ar : fiscalMonthlySales){
                    Integer cm = (Integer)ar.get('CM');
                    Id accountId = (Id)ar.get('Account__c');
                    
                    Account accountUpdate = new Account();
                    accountUpdate.Id = accountId;
                    
                    if(cm == 1){
                        accountUpdate.January_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 2){
                        accountUpdate.February_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 3){
                        accountUpdate.March_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 4){
                        accountUpdate.April_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 5){
                        accountUpdate.May_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 6){
                        accountUpdate.June_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 7){
                        accountUpdate.July_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 8){
                        accountUpdate.August_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 9){
                        accountUpdate.September_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 10){
                        accountUpdate.October_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 11){
                        accountUpdate.November_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    else if(cm == 12){
                        accountUpdate.December_Sales__c = (Decimal)ar.get('total_sales');
                    }
                    
                    accountUpdate.Recalculate_Sales__c = false;
                    updateAccounts.add(accountUpdate);
                }
                
                accountIds = new Set<Id>();
            }
            else{
                continue;
            }
        }
        
        update updateAccounts;

    }

    public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true; 
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
    }
}