force-app/main/default/objects/Account/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Captures the client id. Legacy field from STARs.</description>
    <displayFormat>C{000000}</displayFormat>
    <label>Client ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Contact__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invoice contact doesn&apos;t belong to this account!</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Invoice Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <label>Course Product Line</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Captures Client ID from Account.</description>
    <formula>Account.Client_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Contact__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <description>Captures the client&apos;s purchase order number when booked.</description>
    <label>Purchase Order Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Source Quote</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Training_City__c.field-meta.xml
<CustomField>
    <fullName>Training_City__c</fullName>
    <description>City of the Training address for this Order.</description>
    <inlineHelpText>City of the Training address for this Order.</inlineHelpText>
    <label>Training City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Training_Province__c.field-meta.xml
<CustomField>
    <fullName>Training_Province__c</fullName>
    <description>Province of the Training address for this Order.</description>
    <inlineHelpText>Province of the Training address for this Order.</inlineHelpText>
    <label>Training Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Training_Street__c.field-meta.xml
<CustomField>
    <fullName>Training_Street__c</fullName>
    <description>Street of the Training address for this Order.</description>
    <inlineHelpText>Street of the Training address for this Order.</inlineHelpText>
    <label>Training Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Product&apos;s Duration. Used with Price Rule to set Quantity of Additional Hours Product.</description>
    <inlineHelpText>Product&apos;s Duration. Used with Price Rule to set Quantity of Additional Hours Product.</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the Product&apos;s Family.</description>
    <inlineHelpText>Indicates the Product&apos;s Family.</inlineHelpText>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Scheduled_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_and_Time__c</fullName>
    <description>Captures the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</description>
    <inlineHelpText>Indicates the Scheduled Start date and time of the related Service Appointment (for on-site Service Appointments). Populated once Service Appointment is created via Process Builder rule.</inlineHelpText>
    <label>Scheduled Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Train_the_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Train_the_Trainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captures whether the course Product is delivered as Train-the-Trainer.</description>
    <inlineHelpText>Indicates whether the course Product is delivered as Train-the-Trainer.</inlineHelpText>
    <label>Train-the-Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Training_City__c.field-meta.xml
<CustomField>
    <fullName>Training_City__c</fullName>
    <description>City of the Training address for this Order Product. Pulled from Order for On-Site/Consulting or Service Appointment for Classroom/Evaluations.</description>
    <inlineHelpText>City of the Training address for this Order Product.</inlineHelpText>
    <label>Training City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Training_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Training_Location_Name__c</fullName>
    <description>Name of the Training address for this Order Product. Pulled from Quote for On-Site/Consulting or Service Appointment for Classroom/Evaluations.</description>
    <inlineHelpText>Name of the Training address for this Order Product.</inlineHelpText>
    <label>Training Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Training_Street__c.field-meta.xml
<CustomField>
    <fullName>Training_Street__c</fullName>
    <description>Street of the Training address for this Order Product. Pulled from Order for On-Site/Consulting or Service Appointment for Classroom/Evaluations.</description>
    <inlineHelpText>Street of the Training address for this Order Product.</inlineHelpText>
    <label>Training Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Captures the duration of the course in hours.</description>
    <inlineHelpText>Indicates the duration of the course in hours.</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <description>Captures Client ID from Account.</description>
    <formula>SBQQ__Account__r.Client_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates Client ID from Account.</inlineHelpText>
    <label>Client ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Invoice_Contact__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invoice Contact does not belong to Account!</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Invoice Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <description>Captures the client&apos;s purchase order number at the time of booking.</description>
    <inlineHelpText>Indicates the client&apos;s purchase order number at the time of booking.</inlineHelpText>
    <label>Purchase Order Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderConfirmationController.cls
/***************************************************************************
Name : OrderConfirmationController
Created By : Aditya Chasta
Created Date : 06/26/2017
Description : OrderConfirmationController class for OrderConfirmation visualforce component that will be used in Master Order Confirmation email template
***************************************************************************/
public with sharing class OrderConfirmationController {
    
    public Order orderRecord {get;set;}
    public String recordId {get;set {recordId = value;}} //This will store order record id
    public List<Order> orderList;
    public List<OrderItem> evaluationProductList;
    public List<OrderItem> onsiteProductList;
    public List<OrderItem> publicProductList;
    public List<OrderItem> physicalGoodsProductList;
    public Map<Id, String> orderItemAttendeeMap;
    public Integer countOfOnsiteTTTProducts {get;set;}
    public Integer countOfOnsiteJHSCProducts {get;set;}
    public Integer countOfTTTProducts {get;set;}
    public Integer countOfJHSCProducts {get;set;}
    public Integer countOfConsultingServices {get;set;}
    public List<OrderItem> orderItemsList {get;set;}
    private List<OrderItem> courseProductList;
    private Set<Id> orderItemIdSet;
    private Set<Id> publicProductIdSet;
    private Boolean publicProductAdded;
    private Boolean onsiteProductAdded;
    
    /*
    * Consructor
    */
    public OrderConfirmationController() {
        try {
            System.debug('In Consructor');
            evaluationProductList = new List<OrderItem>();
            courseProductList = new List<OrderItem>();
            onsiteProductList = new List<OrderItem>();
            publicProductList = new List<OrderItem>();
            physicalGoodsProductList = new List<OrderItem>();
            orderItemsList = new List<OrderItem>();
            orderItemAttendeeMap = new Map<Id, String>();
            orderItemIdSet = new Set<Id>();
            publicProductIdSet = new Set<Id>();
            orderList = new List<Order>();
            countOfOnsiteTTTProducts = 0;
            countOfOnsiteJHSCProducts = 0;
            countOfTTTProducts = 0;
            countOfJHSCProducts = 0;
            countOfConsultingServices = 0;
            publicProductAdded = false;
            onsiteProductAdded = false;
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> Constructor : '+e.getMessage()+e.getStackTraceString());
        }
    }
    
    /*
    * Following method will return list of orders
    */
    public List<Order> getOrderList() {
        try {
            orderList = [select Client_ID__c, Invoice_Contact__r.Name, Purchase_Order_Number__c, OrderNumber, BillingStreet, BillingCity, BillingState, BillingPostalCode, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, Account.Name, Owner.Name, Owner.Phone, Owner.Email,Owner.Title from Order where id =: recordId];
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> getEvaluationProductList : '+e.getMessage()+e.getStackTraceString());
        }
        return orderList;
    }
    
    /*
    * Following method will return evaluation orderitems
    */
    public List<OrderItem> getEvaluationProductList() {
        try {
            if(evaluationProductList.size() == 0) {
                evaluationProductList = [select Pricebookentry.Product2.Name , Product_Family__c, Delivery_Method__c, Course_Product_Line__c, Train_the_Trainer__c, 
                                Quantity, Scheduled_Date_and_Time__c, Duration__c, Training_Location_Name__c, SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__ShippingName__c, 
                                Training_Street__c, Training_City__c, Training_Province__c, Training_Postal_Code__c, Parking_Details__c, 
                                Primary_Contact__r.Name, Personal_Protective_Equipment_PPE__c, Primary_Contact__r.Phone, Training_Country__c,
                                Lifting_Device_Eval_Details__c, Annual_Safety_Inspection_Eval_Details__c, TotalPrice, UnitPrice, Scheduled_End_Time__c,
                                Number_of_Participants__c 
                                from OrderItem where orderId =: recordId and Product_Family__c = 'Evaluations'];
                orderItemsList.addAll(evaluationProductList);
            }
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> getEvaluationProductList : '+e.getMessage()+e.getStackTraceString());
        }
        return evaluationProductList;
    }
    
    /*
    * Following method will set course orderitems
    */
    private void setCourseProductList() {
        courseProductList = [select Pricebookentry.Product2.Name , Product_Family__c, Delivery_Method__c, Course_Product_Line__c, Train_the_Trainer__c, 
        Quantity, Scheduled_Date_and_Time__c, Duration__c, Training_Location_Name__c, SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__ShippingName__c, 
        Training_Street__c, Training_City__c, Training_Province__c, Training_Postal_Code__c, Parking_Details__c, Training_Country__c,
        Primary_Contact__r.Name, Personal_Protective_Equipment_PPE__c, Primary_Contact__r.Phone, Scheduled_End_Time__c,
        Lifting_Device_Eval_Details__c, Annual_Safety_Inspection_Eval_Details__c, TotalPrice, UnitPrice, 
        Number_of_Participants__c 
        from OrderItem where orderId =: recordId and Product_Family__c = 'Courses' and (Delivery_Method__c = 'On-site' OR Delivery_Method__c='Classroom')];
        
        for(OrderItem orderProduct : courseProductList) {
            if(orderProduct.Delivery_Method__c == 'On-site') {
                onsiteProductList.add(orderProduct);
                if(orderProduct.Train_the_Trainer__c) {
                    countOfOnsiteTTTProducts++;
                }
                if(orderProduct.Course_Product_Line__c.contains('JHSC')) {
                    countOfOnsiteJHSCProducts++;
                }
            } else if(orderProduct.Delivery_Method__c == 'Classroom') {
                publicProductList.add(orderProduct);
            }
            if(orderProduct.Train_the_Trainer__c) {
                countOfTTTProducts++;
            }
            if(orderProduct.Course_Product_Line__c.contains('JHSC')) {
                countOfJHSCProducts++;
            }
        }
    }
    
    /*
    * Following method will return onsite orderitems
    */
    public List<OrderItem> getOnsiteProductList() {
        try {
            if(courseProductList.size() == 0) {
                setCourseProductList();
            }
            if(!onsiteProductAdded) {
                onsiteProductAdded = true;
                orderItemsList.addAll(onsiteProductList);
            }
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> getOnsiteProductList : '+e.getMessage()+e.getStackTraceString());
        }
        return onsiteProductList;
    }
    
    /*
    * Following method will return public orderitems
    */
    public List<OrderItem> getPublicProductList() {
        try {
            if(courseProductList.size() == 0) {
                setCourseProductList();
            }
            if(!publicProductAdded) {
                publicProductAdded = true;
                orderItemsList.addAll(publicProductList);
            }
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> getPublicProductList : '+e.getMessage()+e.getStackTraceString());
        }
        return publicProductList;
    }
    
    /*
    * Following method will return physical goods orderitems
    */
    public List<OrderItem> getphysicalGoodsProductList() {
        try {
            if(physicalGoodsProductList.size() == 0) {//System.assert(false,recordId);
                physicalGoodsProductList = [select Pricebookentry.Product2.Name , Product_Family__c, Delivery_Method__c, Course_Product_Line__c, Train_the_Trainer__c, 
                Quantity, Scheduled_Date_and_Time__c, Duration__c, Training_Location_Name__c, SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__ShippingName__c, 
                Training_Street__c, Training_City__c, Training_Province__c, Training_Postal_Code__c, Parking_Details__c, Training_Country__c,
                Primary_Contact__r.Name, Personal_Protective_Equipment_PPE__c, Primary_Contact__r.Phone, Other__c, Scheduled_End_Time__c,
                Lifting_Device_Eval_Details__c, Annual_Safety_Inspection_Eval_Details__c, TotalPrice, UnitPrice, 
                Number_of_Participants__c 
                from OrderItem where orderId =: recordId and Product_Family__c = 'Physical Goods'];
                
                orderItemsList.addAll(physicalGoodsProductList);
            }
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> getPhysicalGoodsProductList : '+e.getMessage()+e.getStackTraceString());
        }
        //System.assert(false,physicalGoodsProductList);
        return physicalGoodsProductList;
    }
    
    /*
    * Following method will return count of consulting orderitems
    */
    public Integer getcountOfConsultingServices() {
        Integer consultingServicesCount;
        try {
            consultingServicesCount = [select COUNT() from OrderItem where orderId =: recordId and Product_Family__c = 'Consulting Services' and (Delivery_Method__c = 'Classroom' or Delivery_Method__c = 'On-site' )];
        } catch (Exception e) {
            System.debug('OrderConfirmationController --> getPhysicalGoodsProductList : '+e.getMessage()+e.getStackTraceString());
        }
        return consultingServicesCount;
    }
    
    /*
    * Following method will return order item and attendeeMap
    */
    public Map<Id, String> getOrderItemAttendeeMap() {
        try {
            Set<Id> orderItemIdSet = new Set<Id>();
            if(orderItemsList.size() > 0) {
                for(OrderItem orderProduct : orderItemsList) {
                    orderItemIdSet.add(orderProduct.id);
                }
            }

            List<Attendee__c> attendeeList = [select name, Order_Product__c from Attendee__c where Order_Product__c in: orderItemIdSet];
            String attendeeName = '';
            for(OrderItem orderProduct : orderItemsList) {
                for(Attendee__c attendee : attendeeList) {
                    if(attendee.Order_Product__c == orderProduct.id) {
                        if(orderItemAttendeeMap.containsKey(orderProduct.id)) {
                            if(String.isBlank(orderItemAttendeeMap.get(orderProduct.id))) {
                                orderItemAttendeeMap.put(orderProduct.id, attendee.name);
                            } else {
                                attendeeName = orderItemAttendeeMap.get(orderProduct.id);
                                orderItemAttendeeMap.put(orderProduct.id, attendeeName+', '+attendee.name);
                            }
                        } else {
                            orderItemAttendeeMap.put(orderProduct.id, attendee.name);
                        }
                        
                    }
                }
                if(!orderItemAttendeeMap.containsKey(orderProduct.id)) {
                    orderItemAttendeeMap.put(orderProduct.id,'');
                }
            }            
        } catch(Exception e) {
            System.debug('OrderConfirmationController --> setOrderItemAttendeeMap : '+e.getMessage()+e.getStackTraceString());
        }
        return orderItemAttendeeMap;
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;        
	}    
}