force-app/main/default/objects/Account/fields/Covid_Discount__c.field-meta.xml
<CustomField>
    <fullName>Covid_Discount__c</fullName>
    <label>Covid Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Captures the attendees of a Service Appointment (Course) record. Connects to Contact, Quote Line, Order Product and Service Appointment (Course) objects.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>IF(ISBLANK( Contact__r.Account.ShippingAddress ), 
&apos;&apos;,
Contact__r.Account.ShippingStreet + &apos;, &apos; 
+ Contact__r.Account.ShippingCity + &apos;, &apos; 
+ Contact__r.Account.ShippingState + &apos;, &apos;
+ Contact__r.Account.ShippingPostalCode + &apos;, &apos;
+ Contact__r.Account.ShippingCountry
)</formula>
    <label>Contact&apos;s Account Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <label>Course Product Line</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Order_Product__r.Product2.External_Product_Name__c</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
            <value>
                <fullName>JHSCI</fullName>
            </value>
            <value>
                <fullName>RFTE</fullName>
            </value>
            <value>
                <fullName>TTAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>Captures the promotions available for clients. Utilized to calculate promotion discount on the SBQQ_QuoteLine.</description>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/Promotional_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Code__c</fullName>
    <description>Captures the promotional code. Used as matching variable during quoting.</description>
    <inlineHelpText>Indicates the promotional code. Used as matching variable during quoting.</inlineHelpText>
    <label>Promotional Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Quoted Seats</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product. Populated via Process Rule for use with roll-ups.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable. Populated via Process Rule for use with roll-ups and Price Rules.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the Product&apos;s Family. Populated via Process Rule for use with roll-ups.</description>
    <inlineHelpText>Indicates the Product&apos;s Family.</inlineHelpText>
    <label>RO Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Promotional_Discount__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Discount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Promotion Code</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Promotion is not active or for a different product</errorMessage>
        <filterItems>
            <field>Promotion__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Promotion__c.Applicable_Product__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Product__c</valueField>
        </filterItems>
        <filterItems>
            <field>Promotion__c.All_Products__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Train_the_Trainer__c.field-meta.xml
<CustomField>
    <fullName>Train_the_Trainer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captures whether the course Product is delivered as Train-the-Trainer. Populated upon creation of Quote Line.</description>
    <inlineHelpText>Indicates whether the course Product is delivered as Train-the-Trainer.</inlineHelpText>
    <label>Train-the-Trainer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to the Account. Set based on the Parent Record</description>
    <inlineHelpText>Connection to the Account. Set based on the Parent Record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the course. Pulled from Product.</description>
    <inlineHelpText>Indicates the courses product line. Pulled from Product.</inlineHelpText>
    <label>Course Product Line</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</description>
    <inlineHelpText>Indicates the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>Captures the related Product&apos;s Product Family.</description>
    <formula>TEXT(Product__r.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates the related Product&apos;s Product Family.</inlineHelpText>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteLineTriggerHandler.cls
/**********************************************************************
Name: QuoteLineTriggerHandler
Author : Shubham Verma
Description : Handler class for QuoteLine Trigger

History Log
==========================
2020-12-16		BMathew		Added logic to handle JHSCI Online attendees and when sold as a bundle with JHSCII
**********************************************************************/
public with sharing class QuoteLineTriggerHandler extends TriggerHandler{
    public static Set<Id> classRoomIds;
    public static Set<Id> quoteIds;
    public static Set<Id> quoteLineIds; //set of Quote Line Items
    public static List<String> productCodeExceptions = new List<String>{'TTAL', 'JHSCI'};	//product codes that are exceptions to the standard queryies
    public static Set<String> productCodeExceptionsSet = new Set<String>{'TTAL', 'JHSCI'};
    
    public override void beforeInsert(){
        
        Set<Id> productIds = new Set<Id>();
        classRoomIds = new Set<Id>();
        quoteIds = new Set<Id>();
        try{
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                if(ql.SBQQ__Product__c != Null){
                    productIds.add(ql.SBQQ__Product__c);
                }
                // filter quote line's having classroom course
                if(ql.Classroom_Course__c != Null){
                    classRoomIds.add(ql.Classroom_Course__c);
                }
                if(ql.Classroom_Course__c == Null){
                    quoteIds.add(ql.SBQQ__Quote__c);
                }
            }
            if(productIds.size() > 0){
                // call populateWorkType method to Populate work type on Quote Line with respective product 
                QuoteLineTriggerHandler.populateWorkType(productIds);
            }
            
            if(classRoomIds.size() > 0 || quoteIds.size() > 0){
                // call populateTrainingAddressFields method to populate training address fields on Quote line with rescpective Classroom(SA) address fields
                QuoteLineTriggerHandler.populateTrainingAddressFields();
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
    }
    
    public override void beforeUpdate(){
        
        Set<Id> productIds = new Set<Id>();
        classRoomIds = new Set<Id>();
        quoteIds = new Set<Id>();
        
        try{
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                
                SBQQ__QuoteLine__c oldQL = (SBQQ__QuoteLine__c)Trigger.oldMap.get(ql.id);

                if(ql.Promotional_Discount__c != Null && oldQL.Promotional_Discount__c != ql.Promotional_Discount__c){
					List<Promotion__c> promotions = [Select Id, Promotional_Code__c from Promotion__c where id =: ql.Promotional_Discount__c];
                    
                    for(Promotion__c promo : promotions){
                        if(promo.Promotional_Code__c.indexOf('COVID19') != -1){
                            Account account = [Select Id, Covid_Discount__c from Account where Id = :ql.Account__c][0];
                            Decimal remainingCovidDiscounts = account.Covid_Discount__c;
                            
                            System.debug('REMAINING: ' + remainingCovidDiscounts);
                            if(remainingCovidDiscounts == null){
                                ql.addError('Account has no Covid Discounts!');
                            }
                            else{
                                System.debug('-1: ' + (remainingCovidDiscounts - 1));
                                if((remainingCovidDiscounts - 1) < 0){
                                    ql.addError('No more Covid Discounts remaining!');
                                }
                                else{
                                    account.Covid_Discount__c--;
                                    //update account;
                                }
                            }
                    	}
                    }
                }
                
                if(ql.SBQQ__Product__c != Null && ((SBQQ__QuoteLine__c)Trigger.oldMap.get(ql.Id)).SBQQ__Product__c != ql.SBQQ__Product__c){
                    productIds.add(ql.SBQQ__Product__c);
                }
                // checkin if class room is updated for quote line to update training fields
                if(ql.Classroom_Course__c != Null  && ((SBQQ__QuoteLine__c)Trigger.oldMap.get(ql.Id)).Classroom_Course__c != ql.Classroom_Course__c){
                    classRoomIds.add(ql.Classroom_Course__c);
                }
                if(ql.Classroom_Course__c == Null){
                    quoteIds.add(ql.SBQQ__Quote__c);
                }
            }

            System.debug('#### : '+productIds+'@@@@0'+classRoomIds+'@@@@'+quoteIds);
            
            if(productIds.size() > 0){
                // call populateWorkType method to Populate work type on Quote Line with respective product 
                QuoteLineTriggerHandler.populateWorkType(productIds);
            }
            
            if(classRoomIds.size() > 0 || quoteIds.size() > 0){
                // call populateTrainingAddressFields method to populate training address fields on Quote line with rescpective Classroom(SA) address fields
                QuoteLineTriggerHandler.populateTrainingAddressFields();
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }    
    }
    
    public override void afterInsert(){
        
        quoteLineIds = new Set<Id>();
        Set<Id> quoteIdSet = new Set<Id>();
        classRoomIds = new Set<Id>();
        List<string> ids = new List<string>(); //List of record ids having Train_the_Trainer__c = true
        
        try{
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                quoteIds.add(ql.SBQQ__Quote__c);
                // filte Quote Lines's with Course or Evaluations Product to create attendee records
                if(ql.SBQQ__ProductFamily__c == 'Courses' || ql.SBQQ__ProductFamily__c == 'Evaluations') {
                    System.debug('AFTER INSERT::ID => ' + ql.Id);
                    System.debug(ql.Product_Family__c);
                    System.debug(ql.Course_Product_Line__c);
                    System.debug(ql.SBQQ__Product__r.Delivery_Method__c);                    
                    quoteLineIds.add(ql.Id);
                }
                if(ql.Classroom_Course__c != Null){
                    classRoomIds.add(ql.Classroom_Course__c);
                }
                //Filter record ids having Train_the_Trainer__c = true
                if(ql.Train_the_Trainer__c) {
                    ids.add(ql.id);
                }
            }
            System.debug('ids : '+ids);
            //Code to populate Training Instructor Requirements URL field if Train_the_Trainer__c = true

            system.debug('<<<<--Ids-->>>>'+quoteLineIds);
            if(quoteLineIds.size() > 0){
                System.debug('AFTER INSERT::quoteLineIds =>' + quoteLineIds);
                // call createAttendeeRecord method to create attendee records
                QuoteLineTriggerHandler.createAttendeeRecord(quoteLineIds);
            }
            if(classRoomIds.size() > 0){
                // call updateQuotedSeats metod to update current quoted field on classroom(SA) record
                QuoteLineTriggerHandler.updateQuotedSeats(classRoomIds);
            }
            
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
        
        
    }
    public override void afterUpdate(){
       
        quoteLineIds = new Set<Id>();
        Set<Id> quoteIdSet = new Set<Id>();
        Set<Id> qlIdsOSCQuestion = new Set<Id>(); // Set of Quote Line Id's For pushing data of On-Site Question to related Service Appointment
        classRoomIds = new Set<Id>();
        
        try{
            SBQQ__QuoteLine__c oldQuoteLine = new SBQQ__QuoteLine__c();
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                quoteIds.add(ql.SBQQ__Quote__c);
                oldQuoteLine = (SBQQ__QuoteLine__c)Trigger.oldMap.get(ql.id);
                if(ql.Classroom_Course__c != null){
                    if(oldQuoteLine.Classroom_Course__c != null && oldQuoteLine.Classroom_Course__c != ql.Classroom_Course__c){
                        classRoomIds.add(oldQuoteLine.Classroom_Course__c);    
                    }
                    if(ql.SBQQ__Quantity__c != oldQuoteLine.SBQQ__Quantity__c || oldQuoteLine.Classroom_Course__c == null){
                        classRoomIds.add(ql.Classroom_Course__c);
                    }
                }
                // checking if quatity or no. of participants values updated to create attendee records
                if((ql.SBQQ__ProductFamily__c == 'Courses' || ql.SBQQ__ProductFamily__c == 'Evaluations') && (ql.Number_of_Participants__c != oldQuoteLine.Number_of_Participants__c || ql.SBQQ__Quantity__c != oldQuoteLine.SBQQ__Quantity__c)) {
                    System.debug('AFTER UPDATE::Id => ' + ql.Id);
                    quoteLineIds.add(ql.Id);
                }
                // checking if Quote Line's fields updated which is relate to OSC course questions
                if(ql.Primary_Contact__c != oldQuoteLine.Primary_Contact__c || ql.Lifting_Device_Eval_Details__c != oldQuoteLine.Lifting_Device_Eval_Details__c || ql.Annual_Safety_Inspection_Eval_Details__c != oldQuoteLine.Annual_Safety_Inspection_Eval_Details__c){
                    qlIdsOSCQuestion.add(ql.Id);
                }
                 
            }
            if(qlIdsOSCQuestion.size() > 0 ){
                // call pushOSCQuestionAns to push Ans to related classroom(SA) 
                QuoteLineTriggerHandler.pushOSCQuestionAns(qlIdsOSCQuestion);
            }
            if(quoteLineIds.size() > 0){
                // call createAttendeeRecord method to create attendee records
                QuoteLineTriggerHandler.createAttendeeRecord(quoteLineIds);
            }
            if(classRoomIds.size() > 0){
                // call updateQuotedSeats metod to update current quoted field on classroom(SA) record
                QuoteLineTriggerHandler.updateQuotedSeats(classRoomIds);
            }
            
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }        
    }
    
    
    public override void beforeDelete(){
        String profileName = [select Name from profile where id = :UserInfo.getProfileId()].Name;
        quoteLineIds = new Set<Id>();
        
        try{
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.Old){
				
				//Check if the quote has been sent
				SBQQ__Quote__c q = [Select Send_Date__c from SBQQ__Quote__c where Id =: ql.SBQQ__Quote__c][0];
                if(q.Send_Date__c != NULL && profileName != 'OSG Sys Admin'){
                    ql.addError('Cannot delete quote line! Contact your administrator.');
                }
                // filter Courses and Evaluations Quote lins 
                if((ql.SBQQ__ProductFamily__c == 'Courses' || ql.SBQQ__ProductFamily__c == 'Evaluations')) {
                    quoteLineIds.add(ql.Id);
                }
            }
            if(quoteLineIds.size() > 0){
                // Delete attendee records when ever a quote line deleted
                QuoteLineTriggerHandler.deleteAttendeeRecords(quoteLineIds);
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }    
    }
    
    
    public override void afterDelete(){
        quoteIds = new Set<Id>();
        classRoomIds = new Set<Id>();
        Set<Id> quoteIdSet = new Set<Id>();
        
        try{
            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.Old){
                quoteIds.add(ql.SBQQ__Quote__c);
                if(ql.Classroom_Course__c != null ){
                    classRoomIds.add(ql.Classroom_Course__c);
                }
            }
            if(classRoomIds.size() > 0){
                // call updateQuotedSeats metod to update current quoted field on classroom(SA) record
                QuoteLineTriggerHandler.updateQuotedSeats(classRoomIds);
            }
            if(quoteIds.size() > 0){
                //QuoteLineTriggerHandler.sameDayCourseMatch(quoteIds);
            }
            
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
        
        
    }
    
    // Method to populate work type on Quote line
    // Populate work type with related product on Quote Line
    // Product family should be in ('Evaluations','Consulting Services','Courses') and Delivery Metohd = On-site
    public static void populateWorkType(Set<Id> prodIds){
        
        Map<Id,Id> mapProdWorkType = new Map<Id,Id>();
        // Querying worktype records
        
        try{
            for(WorkType wt : [Select Id,Product__c,Product__r.Family From WorkType Where Product__c IN : prodIds AND (Product__r.Family IN ('Evaluations','Consulting Services','Courses') AND (Product__r.Delivery_Method__c != 'Classroom' OR Product__r.Course_Product_Line__c in :productCodeExceptions))]){
                mapProdWorkType.put(wt.Product__c, wt.Id);
            }
            if(mapProdWorkType.keySet().size() > 0){
                for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                    if(mapProdWorkType.containsKey(ql.SBQQ__Product__c)){
                        ql.Work_Type__c = mapProdWorkType.get(ql.SBQQ__Product__c);
                    }
                }
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
        
        
    }
    
    
    
    // Method to populate training address fields with rescpective classroom(SA) recourd address
    public static void populateTrainingAddressFields(){
        
        Map <Id,ServiceAppointment> mapSA = new Map<Id,ServiceAppointment>();
        
        try{
            if(classRoomIds.size() > 0){
                //Querying Service Appointment records
                for(ServiceAppointment sa : [Select Id, Street, City, State, Country, PostalCode, SchedStartTime From ServiceAppointment Where Id IN: classRoomIds]){
                    mapSA.put(sa.Id,sa);
                }
            }

            for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                if(ql.Classroom_Course__c != Null){
                    if(mapSA.keySet().size() > 0){
                        // Map Training fields with Classroom(SA) address
                        if(mapSA.containsKey(ql.Classroom_Course__c)){
                            ql.Training_Province__c = mapSA.get(ql.Classroom_Course__c).State;
                            ql.Scheduled_Date_and_Time__c = mapSA.get(ql.Classroom_Course__c).SchedStartTime;
                        }
                    }
                }

            }
            
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }  
    }
    
 
    
    // Method to create Attendee Records relted to the Quote Lines
    public static void createAttendeeRecord(set<Id> qlIds){
        List<SBQQ__QuoteLine__c> lstQuoteLine = new List<SBQQ__QuoteLine__c>(); // Quote Line List for creating respective Attendee records 
        
        try{
            // Fatching Quote Line Records  for Knowing Delivery Method of Quote Line
            for(SBQQ__QuoteLine__c ql : [Select Id,SBQQ__Product__c,Account__r.Name, SBQQ__ProductFamily__c, Number_of_Participants__c, SBQQ__Quantity__c, SBQQ__Product__r.Delivery_Method__c, SBQQ__Product__r.Course_Product_Line__c, Course_Product_Line__c From SBQQ__QuoteLine__c Where Id IN : qlIds AND (SBQQ__Product__r.Delivery_Method__c = 'Classroom' OR (SBQQ__Product__r.Delivery_Method__c = 'On-site' and SBQQ__ProductFamily__c = 'Evaluations' and SBQQ__Product__r.Course_Product_Line__c != 'RFTE' and (not Account__r.Name like '%Toyota Motor%')) OR (SBQQ__Product__r.Delivery_Method__c = 'Online' and SBQQ__Product__r.Course_Product_Line__c in :productCodeExceptions))]){
                lstQuoteLine.add(ql);
                System.debug('CREATE ATTENDEE RECORD (FOR LOOP):: ' + ql);
            }
            
            //Map for getting the count of exisiting Attendee records with rescpective Quote Line 
            Map<Id,Integer> countMap = new Map<Id,Integer>();
            for(AggregateResult ar : [Select Count(Id) idCount, Quote_Line__c From Attendee__c Where Quote_Line__c IN :qlIds Group By Quote_Line__c]){
                countMap.put((Id)ar.get('Quote_Line__c'), (Integer)ar.get('idCount'));
            }
            
            System.debug(qlIds);
            //List of newly created attendee records
            List<Attendee__c> lstAttendeeRecords = new List<Attendee__c>();
            for(SBQQ__QuoteLine__c ql :lstQuoteLine){
                Integer startingpoint = 0; //staring point for loop
                Integer endPoint = 0;      //end point of loop
                //setting starting point if already attendee record creted for rescpective Quote Line
                if(countMap.keySet().size() > 0 && countMap.containsKey(ql.Id)){
                    startingpoint = countMap.get(ql.Id); 
                }
                // setting endPoint 
                if((ql.SBQQ__ProductFamily__c == 'Courses' && ql.SBQQ__Product__r.Delivery_Method__c == 'Classroom') || (ql.SBQQ__ProductFamily__c == 'Evaluations')){
                    endPoint = (Integer)ql.SBQQ__Quantity__c;
                }
                if(ql.SBQQ__ProductFamily__c == 'Courses' && ql.SBQQ__Product__r.Delivery_Method__c == 'Online' && productCodeExceptionsSet.contains(ql.SBQQ__Product__r.Course_Product_Line__c)){
                    endPoint = (Integer)ql.SBQQ__Quantity__c;
                }
                if(ql.SBQQ__ProductFamily__c == 'Courses' && ql.SBQQ__Product__r.Delivery_Method__c== 'On-site'){
                    endPoint = (Integer)ql.Number_of_Participants__c;
                }
                system.debug('---Starting Point---'+startingpoint +'******'+endPoint);
                // loop for crating attendee records
                for(Integer i = startingpoint; i< endPoint; i++){
                    Attendee__c atRec = new Attendee__c();
                    atRec.Name = 'TBD';
                    atRec.Quote_Line__c = ql.Id;
                    lstAttendeeRecords.add(atRec);
                }
                
            }
            // insert newly created attendee records
            if(lstAttendeeRecords.size() > 0){
                insert lstAttendeeRecords;
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
    }
    
    
    
    // Method to delete attendee records 
    public static void deleteAttendeeRecords(Set<Id> qlIds){
        List<Attendee__c> lstDelAttendeeRecords = new List<Attendee__c>();
        
        try{
            for(Attendee__c at : [Select Id, Quote_Line__c From Attendee__c Where Quote_Line__c IN : qlIds]){
                lstDelAttendeeRecords.add(at);
            }
            
            if(lstDelAttendeeRecords.size() > 0){
                delete lstDelAttendeeRecords;
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
    }
    
    
    // Method to update current quoted seat on classroom course record
    public static void updateQuotedSeats(Set<Id> classRoomCourseIds){
        //System.assert(false,classRoomCourseIds);
        Map<Id, List<SBQQ__QuoteLine__c>> mapClassroomQLines = new Map<Id, List<SBQQ__QuoteLine__c>>();
        Map<Id, ServiceAppointment> mapServiceAppointment = new Map<Id, ServiceAppointment>();
        
        try{
            for(ServiceAppointment sa : [Select Id, Current_Quoted_Seats__c, Confirmed_Seats__c, (Select Id, SBQQ__Quantity__c From Quote_Lines__r) From ServiceAppointment Where Id IN:classRoomCourseIds]){
                mapClassroomQLines.put(sa.Id, new List<SBQQ__QuoteLine__c>());
                mapServiceAppointment.put(sa.Id, sa);
                for(SBQQ__QuoteLine__c ql : sa.Quote_Lines__r){
                    mapClassroomQLines.get(sa.Id).add(ql);
                }
            }
            //System.assert(false,+'==Map-1=='+mapClassroomQLines+'###Map-2###'+mapServiceAppointment);
            List<ServiceAppointment> updateSALst = new List<ServiceAppointment>();
            if(mapServiceAppointment.keySet().size() > 0){
                for(Id saId : mapServiceAppointment.keySet()){
                    ServiceAppointment updateSA = mapServiceAppointment.get(saId);
                    updateSA.Current_Quoted_Seats__c = 0.0;
                    for(SBQQ__QuoteLine__c ql : mapClassroomQLines.get(saId)){
                        updateSA.Current_Quoted_Seats__c += ql.SBQQ__Quantity__c;
                    }
                    if(updateSA.Confirmed_Seats__c == null){
                        updateSA.Confirmed_Seats__c = 0;
                    }
                    
                    updateSA.Current_Quoted_Seats__c += updateSA.Confirmed_Seats__c;
                    updateSALst.add(updateSA);
                }
            }

            if(updateSALst.size() > 0){
                try{
                    update updateSALst;
                }
                catch(Exception e){
                    System.assert(false, e.getMessage() +'=====' + e.getLinenumber());
                }
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
    }
    
    
    
    // Method to push On-Site Course Question's Answers to related Service Appointment of Quote Line
    public static void pushOSCQuestionAns(Set<Id> qlIds){
        Map<Id,ServiceAppointment> mapQLServiceAppointment = new Map<Id,ServiceAppointment>();
        
        try{
            // Fatching Service Appointment Records related
            for(ServiceAppointment sa : [Select Id, Quote_Line__c From ServiceAppointment Where Quote_Line__c IN : qlIds]){
                mapQLServiceAppointment.put(sa.Quote_Line__c, sa);
            }
            
            List<ServiceAppointment> serviceAppointmentLstToUpdate = new List<ServiceAppointment>();
            if(mapQLServiceAppointment.keySet().size() > 0){
              
                for(SBQQ__QuoteLine__c ql : (List<SBQQ__QuoteLine__c>) Trigger.New){
                    if(mapQLServiceAppointment.containsKey(ql.id)){
                        ServiceAppointment updateSA = mapQLServiceAppointment.get(ql.Id);
                        updateSA.ContactId = ql.Primary_Contact__c;
                        updateSA.Lifting_Device_Eval_Details__c = ql.Lifting_Device_Eval_Details__c;
                        updateSA.Annual_Safety_Inspection_Eval_Details__c = ql.Annual_Safety_Inspection_Eval_Details__c;
                        serviceAppointmentLstToUpdate.add(updateSA);
                    }
                }
            }
            
            if(serviceAppointmentLstToUpdate.size() > 0){
                update serviceAppointmentLstToUpdate;
            }
        }
        catch(Exception e){
            System.debug('Error In Quote Line: '+e.getMessage()+e.getStackTraceString()); 
        }
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;        
	}    
}