force-app/main/default/objects/Account/fields/Fiscal_Year_Goal__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_Goal__c</fullName>
    <label>Fiscal Year Goal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recalculate_Monthly_Goals__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Monthly_Goals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Monthly Goals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recalculate_Quarterly_Goals__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Quarterly_Goals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Quarterly Goals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recalculate_Sales__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/CRM_Statement_Id__c.field-meta.xml
<CustomField>
    <fullName>CRM_Statement_Id__c</fullName>
    <label>CRM Statement Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SalesGoalFlaggingTool.cls
public class SalesGoalFlaggingTool implements Schedulable{
    public void execute(SchedulableContext sc){
        flagAccounts();
    }

    public static void flagAccounts(){
        Date today = Date.today();
        Integer todayDate = today.day();
        Integer daysInMonth = Date.daysInMonth(today.year(), today.month());

        Period period = [SELECT FiscalYearSettings.Name, Number, FullyQualifiedLabel, StartDate, EndDate FROM Period WHERE Type = 'Quarter' AND StartDate <= TODAY AND EndDate >= TODAY];
        Date fqEnd = period.EndDate;

        List<Account> accounts = new List<Account>();

        if(todayDate == daysInMonth){
            if(today == fqEnd){
                List<Account> quarterlyAccounts = [Select Id, Recalculate_Monthly_Goals__c, Recalculate_Quarterly_Goals__c, Recalculate_Sales__c from Account where Recalculate_Quarterly_Goals__c = false and Fiscal_Year_Goal__c != null limit 2000];
                for(Account account : quarterlyAccounts){
                    account.Recalculate_Quarterly_Goals__c = true;
                    account.Recalculate_Sales__c = true;
                }

                accounts.addAll(quarterlyAccounts);
            }
            else{
                List<Account> monthlyAccounts = accounts = [Select Id, Recalculate_Monthly_Goals__c, Recalculate_Quarterly_Goals__c, Recalculate_Sales__c from Account where Recalculate_Monthly_Goals__c = false and Fiscal_Year_Goal__c != null limit 2000];
                for(Account account : monthlyAccounts){
                    account.Recalculate_Monthly_Goals__c = true;
                    account.Recalculate_Sales__c = true;
                }

                accounts.addAll(monthlyAccounts);
            }
        }
        else{
            List<Account> salesCalculateAccounts = new List<Account>();
            List<AggregateResult> result = [Select AccountId from Order where Crm_Statement_Id__c = NULL and CreatedDate = LAST_N_DAYS:1 and Account.Recalculate_Sales__c = false group by AccountId];
            for(AggregateResult ar : result){
                Id accountId = (Id)ar.get('AccountId');
                
                Account account = new Account(
                    Id = accountId,
                    Recalculate_Sales__c = true
                );
                salesCalculateAccounts.add(account);
            }

            accounts.addAll(salesCalculateAccounts);
        }


        if(accounts.size() > 0){
            update accounts;
        }
    }

    public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true; 
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
    }
}