force-app/main/default/objects/Account/fields/Invoice_Contact__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Invoice contact doesn&apos;t belong to this account!</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Invoice Contact)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Note__c/Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{000000000}</displayFormat>
        <label>Credit Note ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>Credit_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Contact__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreditNoteTriggerHandlerTest.cls
@isTest
public class CreditNoteTriggerHandlerTest {
    @isTest (SeeAllData=true)
    static void deployTrigger(){
        Account acc = (Account) SmartFactory.createSObject('Account');
        insert acc;        
        
        Pricebook2 pb = (Pricebook2)SmartFactory.createSObject('Pricebook2');
        pb.IsActive=TRUE;
        insert pb;        
        
        Contact contact = [Select Id from Contact limit 1];
        
        Order ord = (Order) SmartFactory.createSObject('Order',new Map<String,Object>{'AccountId'=> acc.id,'EffectiveDate' => System.today(),'Pricebook2Id'=>pb.id, 'Invoice_Contact__c'=>contact.Id});
        insert ord;
        
        Credit_Note__c creditNote = (Credit_Note__c) SmartFactory.createSObject('Credit_Note__c',new Map<String,Object>{'Name'=> '123-Test', 'Account__c'=>acc.Id, 'Order__c'=>ord.Id});
        insert creditNote;
        
        delete creditNote;            
    }
    
    @isTest
    static void doTestCodeCoverage(){
        CreditNoteTriggerHandler.TestCodeCoverage();
    }   
}