force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Location Addresses with Accounts. Also links to Quotes.</description>
    <label>Account Address</label>
    <nameField>
        <label>Address Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Captures the relationship to the Account. Primary relationship.</description>
    <inlineHelpText>Indicates the relationship to the Account. Primary relationship.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Province_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_State_Code__c</fullName>
    <formula>Location_Address__r.Province_State_Code__c</formula>
    <label>Province/State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Captures the type of Account Address.</description>
    <inlineHelpText>Indicates the type of Account Address.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown Address</fullName>
                <default>true</default>
                <label>Unknown Address</label>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Training Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Amount__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Amount__c</fullName>
    <label>Shipping Amount</label>
    <summarizedField>OrderItem.Shipping_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.SBQQ__Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Tax__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Tax__c</fullName>
    <label>Shipping Tax</label>
    <summarizedField>OrderItem.Shipping_Tax__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.SBQQ__Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to Accounts for easier visibility.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Amazon_Sku__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Sku__c</fullName>
    <label>Amazon Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Net_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Unit_Price__c</fullName>
    <formula>UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax__c</fullName>
    <label>Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__OrderedQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__OrderedQuantity__c</fullName>
    <description>The actual quantity of the product placed in the order.</description>
    <inlineHelpText>The actual quantity of the product placed in the order.</inlineHelpText>
    <label>Ordered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipLabel>Order Products (Shipping Address)</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipping_Amount__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Amount__c</fullName>
    <label>Shipping Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ShipStation_Sku__c.field-meta.xml
<CustomField>
    <fullName>ShipStation_Sku__c</fullName>
    <label>ShipStation Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Captures the Tax Rate applicable to this Order Product based on the Province.</description>
    <inlineHelpText>Indicates the Tax Rate applicable to this Order Product based on the Province.</inlineHelpText>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Amount_Without_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Without_Tax__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Total_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Net_Price__c</fullName>
    <label>Total Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/Shipping_Item__c.object-meta.xml
<CustomObject>
    <label>Shipping Item</label>
    <nameField>
        <label>Shipping Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Item__c/fields/Amazon_Sku__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Sku__c</fullName>
    <label>Amazon Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Fulfilled_By_Amazon__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_By_Amazon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fulfilled By Amazon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipped__c.field-meta.xml
<CustomField>
    <fullName>Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/ShipStation_Sku__c.field-meta.xml
<CustomField>
    <fullName>ShipStation_Sku__c</fullName>
    <label>ShipStation Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Rate__c/Tax_Rate__c.object-meta.xml
<CustomObject>
    <description>Captures the tax rates for each region. Utilized to calculate tax on the SBQQ_QuoteLine.</description>
    <label>Tax Rate</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Tax Rate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Rate__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>Captures the Tax Rate for the province.</description>
    <inlineHelpText>Indicates the Tax Rate for the province.</inlineHelpText>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PhysicalGoodOrderController.cls
/***************************
Class Name: PhysicalGoodOrderController
Author: Blessen Mathew
Description: To handle modifications to physical good order products

History Log
=====================================
2018-12-31		BMathew		Created initial class
2019-03-24		BMathew		Adjust logic to now include Shipping_Item__c
****************************/
public class PhysicalGoodOrderController {
    
    @AuraEnabled
    //Determines if shipping item can be modified
    public static String getShippingItemStatus(Id shippingItemId){
        Shipping_Item__c shippingItem = [Select Order_Product__r.SBQQ__Status__c, Fulfilled_By_Amazon__c, Amazon_Sku__c, ShipStation_SKU__c, Shipped__c from Shipping_Item__c where id = :shippingItemId];
        if(shippingItem.Order_Product__r.SBQQ__Status__c != 'Draft' || shippingItem.Fulfilled_By_Amazon__c == TRUE || shippingItem.Shipped__c == TRUE || shippingItem.ShipStation_SKU__c != null){
            return 'INVALID';
        }
        else{
            return 'VALID';
        }
    }
    
    @AuraEnabled
    //Reduce the ordered quantity on the specified shipping items order product    
    public static Boolean reduceShippingQuantity(Id shippingItemId, Decimal newQuantity){
        try{
            Shipping_Item__c shippingItem = [Select Quantity__c, Order_Product__c from Shipping_Item__c where id = :shippingItemId];
            OrderItem op = [Select Id, Shipping_Amount__c, Shipping_Tax__c, SBQQ__Status__c, SBQQ__OrderedQuantity__c, Quantity, Total_Amount_Without_Tax__c, Net_Unit_Price__c, Tax_Rate__c, Sales_Tax__c, Total_Net_Price__c from OrderItem where id = :shippingItem.Order_Product__c];
            
            if(op.SBQQ__Status__c != 'Draft'){
                op.SBQQ__Status__c = 'Draft';
                update op;
            }
            
            Decimal originalQuantity = op.SBQQ__OrderedQuantity__c;
            //update cost based on the new quantity
            op.SBQQ__OrderedQuantity__c = newQuantity;            
            op.Total_Amount_Without_Tax__c = op.Net_Unit_Price__c * newQuantity;
            Decimal salesTax = (op.Net_Unit_Price__c * newQuantity) * (op.Tax_Rate__c/100);
            salesTax = salesTax.setScale(2);
            op.Sales_Tax__c = salesTax;
            op.Total_Net_Price__c = (op.Net_Unit_Price__c * newQuantity) + salesTax;

			//Reduce the shipping amount by 75% of the difference of the quantities
            Decimal difference = (originalQuantity - newQuantity) * .75;
            
            op.Shipping_Amount__c = op.Shipping_Amount__c - difference; 
            Decimal shippingTax = op.Shipping_Amount__c * (op.Tax_Rate__c/100);
            shippingTax = shippingTax.setScale(2);
            op.Shipping_Tax__c = shippingTax;
            update op;
     
            //op.Quantity--;
            //update op;
            
            shippingItem.Quantity__c = newQuantity;
            update shippingItem;
            
            return true;
        }
        catch(Exception e){
            return false;
        }
    }
    
    @AuraEnabled
    //Cancels a shipping Items order product    
    public static Boolean cancelShippingItem(Id shippingItemId){
        try{
            Shipping_Item__c shippingItem = [Select Order_Product__c from Shipping_Item__c where id = :shippingItemId];
            OrderItem op = [Select SBQQ__Status__c from OrderItem where id = :shippingItem.Order_Product__c];
            op.SBQQ__Status__c = 'Canceled';
            update op;
            return true;            
        }
        catch(Exception e){
            return false;
        }
    }
      
    /*
     * THIS MAY BE NEEDED IN FUTURE
     * 
    //Return all valid shipping addresses
    @AuraEnabled
    public static List<Account_Address__c> getShippingAddresses(Id orderProductId){
        //get all the shipping account addresses, in ontario from both the order product account and OSG (official)
        OrderItem oi = [Select Account__c from OrderItem where Id = :orderProductId];
        List<Account_Address__c> shippingAddresses;
        shippingAddresses = [Select Name, Id from Account_Address__c where Type__c = 'Shipping Address' and (Account__c = :oi.Account__c or Account__c = '00146000011bdVXAAY') and Province_State_Code__c = 'ON'];        
        return shippingAddresses;
    }
    
    //set the shipping address on the order product to the Id passed in
    @AuraEnabled
    public static Boolean changeShippingAddress(Id orderProductId, Id accountAddressId){
        try{
            OrderItem oi = [Select Shipping_Address__c from OrderItem where Id = :orderProductId];
			oi.Shipping_Address__c = accountAddressId;
            return true;
        }
        catch(Exception e){
            return false;
        }
    }
*/
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
	}    
}