force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Location Addresses with Accounts. Also links to Quotes.</description>
    <label>Account Address</label>
    <nameField>
        <label>Address Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Location_Address__c</fullName>
    <description>Captures the relationship to the Location Address. Secondary relationship. Contains a lookup filter to the Location: Location Status = Active.</description>
    <inlineHelpText>Indicates the relationship to the Location Address. Secondary relationship. Filter to only display &quot;Active&quot; Location Addresses.</inlineHelpText>
    <label>Location Address</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No &quot;Active&quot; Location Addresses meets the search criteria. Please search for an alternate &quot;Active&quot; Location Address record or create a new one.</errorMessage>
        <filterItems>
            <field>Location_Address__c.Location_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select from &quot;Active&quot; Location Addresses.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location_Address__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Province_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_State_Code__c</fullName>
    <formula>Location_Address__r.Province_State_Code__c</formula>
    <label>Province/State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/Location_Address__c.object-meta.xml
<CustomObject>
    <description>Tracks the location addresses for clients, vendors and OSG. Global data set that can link to one or more Accounts.</description>
    <label>Location Address</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <description>Captures the street address of the location.</description>
    <inlineHelpText>Indicates the street address of the location.</inlineHelpText>
    <label>Address 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/Address_2__c.field-meta.xml
<CustomField>
    <fullName>Address_2__c</fullName>
    <description>Captures the additional street address of the location.</description>
    <inlineHelpText>Indicates the additional street address of the location.</inlineHelpText>
    <label>Address 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Captures the city of the location.</description>
    <inlineHelpText>Indicates the city of the location.</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <formula>CASE( Country__c , 
&quot;Canada&quot;, &quot;CA&quot;, 
&quot;United States&quot;, &quot;US&quot;, 
&quot;&quot;)</formula>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Location_Address__c</fullName>
    <description>Concatenates the entire address fields.</description>
    <formula>Address__c + BR() + City__c + &quot; &quot;+ TEXT(Province__c) + BR() + Postal_Code__c + BR() + TEXT(Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Concatenates the entire address fields.</inlineHelpText>
    <label>Location Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Captures the postal code of the location.</description>
    <inlineHelpText>Indicates the postal code of the location.</inlineHelpText>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/Province_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Province_State_Code__c</fullName>
    <formula>Case (Province__c, 
&quot;Alabama&quot;, &quot;AL&quot;, 
&quot;Alaska&quot;, &quot;AK&quot;, 
&quot;Arizona&quot;, &quot;AZ&quot;, 
&quot;Arkansas&quot;, &quot;AR&quot;, 
&quot;California&quot;, &quot;CA&quot;, 
&quot;Colorado&quot;, &quot;CO&quot;, 
&quot;Connecticut&quot;, &quot;CT&quot;, 
&quot;Delaware&quot;, &quot;DE&quot;, 
&quot;Florida&quot;, &quot;FL&quot;, 
&quot;Georgia&quot;, &quot;GA&quot;, 
&quot;Hawaii&quot;, &quot;HI&quot;, 
&quot;Idaho&quot;, &quot;ID&quot;, 
&quot;Illinois&quot;, &quot;IL&quot;, 
&quot;Indiana&quot;, &quot;IN&quot;, 
&quot;Iowa&quot;, &quot;IA&quot;, 
&quot;Kansas&quot;, &quot;KS&quot;, 
&quot;Kentucky&quot;, &quot;KY&quot;, 
&quot;Louisiana&quot;, &quot;LA&quot;, 
&quot;Maine&quot;, &quot;ME&quot;, 
&quot;Maryland&quot;, &quot;MD&quot;, 
&quot;Massachusetts&quot;, &quot;MA&quot;, 
&quot;Michigan&quot;, &quot;MI&quot;, 
&quot;Minnesota&quot;, &quot;MN&quot;, 
&quot;Mississippi&quot;, &quot;MS&quot;, 
&quot;Missouri&quot;, &quot;MO&quot;, 
&quot;Montana&quot;, &quot;MT&quot;, 
&quot;Nebraska&quot;, &quot;NE&quot;, 
&quot;Nevada&quot;, &quot;NV&quot;, 
&quot;New Hampshire&quot;, &quot;NH&quot;, 
&quot;New Jersey&quot;, &quot;NJ&quot;, 
&quot;New Mexico&quot;, &quot;NM&quot;, 
&quot;New York&quot;, &quot;NY&quot;, 
&quot;North Carolina&quot;, &quot;NC&quot;, 
&quot;North Dakota&quot;, &quot;ND&quot;, 
&quot;Ohio&quot;, &quot;OH&quot;, 
&quot;Oklahoma&quot;, &quot;OK&quot;, 
&quot;Oregon&quot;, &quot;OR&quot;, 
&quot;Pennsylvania&quot;, &quot;PA&quot;, 
&quot;Rhode Island&quot;, &quot;RI&quot;, 
&quot;South Carolina&quot;, &quot;SC&quot;, 
&quot;South Dakota&quot;, &quot;SD&quot;, 
&quot;Tennessee&quot;, &quot;TN&quot;, 
&quot;Texas&quot;, &quot;TX&quot;, 
&quot;Utah&quot;, &quot;UT&quot;, 
&quot;Vermont&quot;, &quot;VT&quot;, 
&quot;Virginia&quot;, &quot;VA&quot;, 
&quot;Washington&quot;, &quot;WA&quot;, 
&quot;West Virginia&quot;, &quot;WV&quot;, 
&quot;Wisconsin&quot;, &quot;WI&quot;, 
&quot;Wyoming&quot;, &quot;WY&quot;, 
&quot;Ontario&quot;, &quot;ON&quot;, 
&quot;Quebec&quot;, &quot;QC&quot;, 
&quot;British Columbia&quot;, &quot;BC&quot;, 
&quot;Alberta&quot;, &quot;AB&quot;, 
&quot;Manitoba&quot;, &quot;MB&quot;, 
&quot;Saskatchewan&quot;, &quot;SK&quot;, 
&quot;Nova Scotia&quot;, &quot;NS&quot;, 
&quot;New Brunswick&quot;, &quot;NB&quot;, 
&quot;Newfoundland And Labrador&quot;, &quot;NL&quot;, 
&quot;Prince Edward Island&quot;, &quot;PE&quot;, 
&quot;Northwest Territories&quot;, &quot;NT&quot;, 
&quot;Yukon&quot;, &quot;YT&quot;, 
&quot;Yukon Territories&quot;, &quot;YT&quot;, 
&quot;Nunavut&quot;, &quot;NU&quot;,
&quot;Oxfordshire&quot;, &quot;OXF&quot;
,&quot;&quot;)</formula>
    <label>Province/State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/Shipping_Item__c.object-meta.xml
<CustomObject>
    <label>Shipping Item</label>
    <nameField>
        <label>Shipping Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Item__c/fields/Amazon_Shipping_Date__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Shipping_Date__c</fullName>
    <label>Amazon Shipping Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Estimated_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Arrival_Date__c</fullName>
    <label>Estimated Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Fulfilled_By_Amazon__c.field-meta.xml
<CustomField>
    <fullName>Fulfilled_By_Amazon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fulfilled By Amazon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Fulfillment_Errors__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Errors__c</fullName>
    <label>Fulfillment Errors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Fulfillment_Id__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Id__c</fullName>
    <label>Fulfillment Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ship To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipped__c.field-meta.xml
<CustomField>
    <fullName>Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Courrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Courrier__c</fullName>
    <label>Shipping Courrier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Canada Post</fullName>
            </value>
            <value>
                <fullName>Canpar</fullName>
            </value>
            <value>
                <fullName>Couriers Plus</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>FedEx</fullName>
            </value>
            <value>
                <fullName>Local Pickup</fullName>
            </value>
            <value>
                <fullName>OSS Supplier</fullName>
            </value>
            <value>
                <fullName>Purolator</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Status__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Status__c</fullName>
    <label>Shipping Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AmazonHelper.cls
/***************************
Class Name: AmazonHelper
Author: Blessen Mathew
Description: Class that sends amazon products to API that will then be sent to Amazon to fulfill

History Log
=====================================
2018-08-20		BMathew		Created initial class
2018-11-21		BMathew		Adjusted logic and updated SentToAmazon field on Order
2018-12-18		BMathew		Adjusted queries to reflect changes (Shipping information on order product instead of order)
2019-01-19		BMathew		Adjusted Fulfilled_By_Amazon to order product from order
2019-03-14		BMathew		Added JHSC Poster logic to handle new business logic
2019-03-29		BMathew		Adding logic to handle 2019 greenbook and greenbook holders. Added generic API parsing functions and classes
2019-04-29		BMathew		Adjusted shipping callout function to handle multiple FulfillmentShipmentPackage members in JSON (Multiple shipping packages)
2022-01-20      BMathew     Testing deploy comment
****************************/
public class AmazonHelper {
    
    //Base amazon good to extend from
    public virtual class AmazonGood{
        public String uniqueIdentifier;
        public String shipping_address;
        public String shipping_city;
        public String shipping_province;
        public String shipping_country;
        public String shipping_postalcode;
        public String shipping_email;
        public String invoice_contact;
        public Integer quantity;         
    }
    
    //Object that Amazon Fulfillment API expects for JHSC Posters
    public class AmazonPoster extends AmazonGood{
    }
    
    //Object that API expects to retreive shipping details
    public class AmazonShipping{
        public string id;
    }
    
    //Processes JHSC Posters and groups based on location and constructs list of JSON objects to be passed to API
    @Future(callout=true)
    public static void processPosterOrders(Set<Id> orders, List<String> JHSCPosterIds){
        //NEEDED TO PASS DEPLOY CODE COVERAGE
        if(Test.isRunningTest()){
            
        }
        else{
            List<Shipping_Item__c> fulfillShippingItems = new List<Shipping_Item__c>();
            List<AmazonPoster> jsonObjects = new List<AmazonPoster>();
            for(Id orderId : orders){
                List<AggregateResult> posterGroup = [Select Shipping_Address__c, Ship_To_Contact__c, Fulfillment_Id__c from Shipping_Item__c where Order__c = :orderId and Product__c in :JHSCPosterIds group by Shipping_Address__c, Ship_To_Contact__c, Fulfillment_Id__c];
                for(AggregateResult result : posterGroup){
                    Id accountAddressId = (Id)result.get('Shipping_Address__c');
                    Id shipToContactId = (Id)result.get('Ship_To_Contact__c');
                    String fulfillmentId = (String)result.get('Fulfillment_Id__c');
                    
                    Location_Address__c locationAddress = [Select Id, Address_1__c, Address_2__c, City__c, Province_State_Code__c, Country_Code__c, Postal_Code__c from Location_Address__c Where id in (Select Location_Address__c from Account_Address__c where id =: accountAddressId)];
                    Contact shipToContact = [Select Id, Name, Email from Contact where Id = :shipToContactId];
                                    
                    AmazonPoster ap = new AmazonPoster();
                    ap.uniqueIdentifier = fulfillmentId;
                    ap.shipping_address = locationAddress.Address_1__c;   
                    if(locationAddress.Address_2__c != NULL){
                        ap.shipping_address += ' ' + locationAddress.Address_2__c;
                    }
                    ap.shipping_city = locationAddress.City__c;
                    ap.shipping_province = locationAddress.Province_State_Code__c;
                    ap.shipping_country = locationAddress.Country_Code__c;
                    ap.shipping_postalcode = locationAddress.Postal_Code__c;
                    ap.invoice_contact = shipToContact.Name;
                    ap.shipping_email = shipToContact.Email;
                    ap.quantity = 0;
                    
                    List<Shipping_Item__c> shippingItems = [Select Quantity__c, Fulfilled_By_Amazon__c, Shipped__c, Shipping_Courrier__c, Fulfillment_Id__c, Fulfillment_Errors__c from Shipping_Item__c where Fulfillment_Id__c =: fulfillmentId];
                    for(Shipping_Item__c shippingItem : shippingItems){
                        ap.quantity = (Integer)(shippingItem.Quantity__c);
                                           
                        fulfillShippingItems.add(shippingItem);
                    }
                    jsonObjects.add(ap);
                }
            }
            
            if(jsonObjects.size() > 0){
	            AmazonHelper.processItems(jsonObjects, fulfillShippingItems, 'callout:Amazon_Posters');
            }
        }
    }    
    
    @AuraEnabled
    @Future(callout=true)
    public static void getAmazonShippingDetails(String recordId, String fulfillmentId){
        AmazonShipping amazonShipping = new AmazonShipping();
        amazonShipping.id = fulfillmentId;
        
        AmazonHelper.amazonShippingCallout(recordId, amazonShipping);
    }
    
    public static void amazonShippingCallout(String recordId, AmazonShipping amazonShipping){
        String trackingNumber = '';
        String estimatedArrivalDate = '';
        String carrierCode = '';
        String shippingDateTime = '';
        String fulfillmentShipmentStatus = '';
        DateTime amazonShippingDateTime = NULL;
        
        Map<String,Object> responseMap = NULL;
        Map<String,Object> fulfillmentShipmentMap = NULL;
        List<Object> fulfillmentShipmentMemberList = NULL;
        Object fulfillmentShipmentMemberObject = NULL;
        Map<String,Object> fulfillmentShipmentMemberMap = NULL;
        Map<String,Object> fulfillmentShipmentPackageMap = NULL;
        List<Object> fulfillmentShipmentPackageMemberList = NULL;
        Object fulfillmentShipmentPackageMemberObject = NULL;
        Map<String,Object> fulfillmentShipmentPackageMemberMap = NULL;
        
        Shipping_Item__c shippingItem = [Select Id, Amazon_Shipping_Date__c, Estimated_Arrival_Date__c, Fulfillment_Errors__c, Shipping_Courrier__c, Shipping_Status__c, Tracking_Number__c from Shipping_Item__c where id = :recordId];
        
        String jsonString = JSON.serialize(amazonShipping);
        HttpResponse response = AmazonHelper.apiCallout(jsonString, 'callout:Amazon_Shipping');
		System.debug('DATA RETURN: ' + response.getBody());
                
        //Push data into map so it can be parsed for required details
		String details = response.getBody();
        responseMap = (Map<String, Object>) JSON.deserializeUntyped(details);
        
        //check initial response contains data
        if(responseMap == NULL || responseMap.isEmpty()){
            shippingItem.Fulfillment_Errors__c = 'There was a fatal error retreiving details. Contact your administrator.';
        }
        else{
            //Check the fulfillmentShipment contains data
            if(!responseMap.containsKey('FulfillmentShipment') || !((Map<String,Object>)responseMap.get('FulfillmentShipment')).containsKey('member')){
				shippingItem.Fulfillment_Errors__c = 'There was an error retrieving shipping details. Try again later.';            
            }
            else{
                fulfillmentShipmentMap = ((Map<String,Object>)responseMap.get('FulfillmentShipment'));
                
                //try to convert the fulfillmentShipment member into a list, if that fails it is a single JSON object
                try{
                    fulfillmentShipmentMemberList = ((List<Object>)fulfillmentShipmentMap.get('member'));
                }
                catch(Exception e){
                    fulfillmentShipmentMemberList = new List<Object>();
                    fulfillmentShipmentMemberList.add((Object)fulfillmentShipmentMap.get('member'));
                }

                if(fulfillmentShipmentMemberList != NULL){
                    //loop through each fulfillmentShipment member
                    for(Object shipmentMember : fulfillmentShipmentMemberList){
                        fulfillmentShipmentMemberMap = ((Map<String,Object>)shipmentMember);
                        
                        if(!fulfillmentShipmentMemberMap.containsKey('FulfillmentShipmentPackage') || !((Map<String,Object>)fulfillmentShipmentMemberMap.get('FulfillmentShipmentPackage')).containsKey('member')){
                            shippingItem.Fulfillment_Errors__c = 'There are no shipping updates yet. Please check again later.';
                        }
                        else{
                            fulfillmentShipmentPackageMap = ((Map<String,Object>)fulfillmentShipmentMemberMap.get('FulfillmentShipmentPackage'));
                            
                            try{
                                fulfillmentShipmentPackageMemberList = ((List<Object>)fulfillmentShipmentPackageMap.get('member'));
                            }
                            catch(Exception e){
                                fulfillmentShipmentPackageMemberList = new List<Object>();
                                fulfillmentShipmentPackageMemberList.add((Object)fulfillmentShipmentPackageMap.get('member'));
                            }
                            
                            if(fulfillmentShipmentPackageMemberList != NULL){
                                for(Object packageMember : fulfillmentShipmentPackageMemberList){
                                    fulfillmentShipmentPackageMemberMap = ((Map<String,Object>)packageMember);
                                    if(trackingNumber != '' && trackingNumber.length() > 0){
                                        trackingNumber += ', ';
                                    }
                                    trackingNumber += (String)fulfillmentShipmentPackageMemberMap.get('TrackingNumber');
                                }
                            }
                            else{
                                //Shouldn't hit this
								shippingItem.Fulfillment_Errors__c = 'There was a fatal error! (FulfillmentShipmentPackageMemberList Empty)';
                            }
                        }
                    }
                    
                    //If both lists have contents then use the data to update sf
                    if(fulfillmentShipmentMemberList != NULL && fulfillmentShipmentPackageMemberList!= NULL){
                        fulfillmentShipmentMemberObject = fulfillmentShipmentMemberList[0];
                        fulfillmentShipmentMemberMap = ((Map<String,Object>)fulfillmentShipmentMemberObject);
                        
                        fulfillmentShipmentPackageMemberObject = fulfillmentShipmentPackageMemberList[0];
                        fulfillmentShipmentPackageMemberMap = ((Map<String,Object>)fulfillmentShipmentPackageMemberObject);
                        
                        estimatedArrivalDate = (String)fulfillmentShipmentPackageMemberMap.get('EstimatedArrivalDateTime');
                        carrierCode = (String)fulfillmentShipmentPackageMemberMap.get('CarrierCode');
                        shippingDateTime = (String)fulfillmentShipmentMemberMap.get('ShippingDateTime');
                        amazonShippingDateTime = (DateTime)JSON.deserialize('"' + shippingDateTime + '"', DateTime.class);
                        fulfillmentShipmentStatus = (String)fulfillmentShipmentMemberMap.get('FulfillmentShipmentStatus');
                        
                        shippingItem.Estimated_Arrival_Date__c = Date.valueOf(estimatedArrivalDate);
                        shippingItem.Tracking_Number__c = trackingNumber;
                        shippingItem.Shipping_Courrier__c = carrierCode;
                        shippingItem.Amazon_Shipping_Date__c = amazonShippingDateTime;
                        shippingItem.Shipping_Status__c = fulfillmentShipmentStatus;
                        shippingItem.Fulfillment_Errors__c = '';         
                    }
                    
                }
                else{
                    //Shouldn't hit this
                    shippingItem.Fulfillment_Errors__c = 'There was a fatal error! (FulfillmentShipmentMemberList Empty)';
                }                
            }                
        }
        
		update shippingItem;
    }
    
    //Takes list of Amazon Goods as JSON, list of associated Shipping Items and the endpoint and updates shipping items
    public static void processItems(List<AmazonGood> amazonJSON, List<Shipping_Item__c> shippingItems, String endpoint){
        for(AmazonGood amazonGood : amazonJSON){
            String json = JSON.serialize(amazonGood);
            System.debug('AMAZON JSON: ' + json);
            HttpResponse response = AmazonHelper.apiCallout(json, endpoint);
            
            //System.debug(response.getBody());
            
            for(Shipping_Item__c shippingItem : shippingItems){
                if(shippingItem.Fulfillment_Id__c == amazonGood.uniqueIdentifier){
                    if(response.getStatusCode() == 200){
                        shippingItem.Fulfilled_By_Amazon__c = TRUE;
                        shippingItem.Shipped__c = TRUE;
                        shippingItem.Shipping_Courrier__c = 'Amazon';
                        shippingItem.Fulfillment_Errors__c = '';
                    }
                    else{
                     	shippingItem.Fulfillment_Errors__c = 'CALLOUT ERROR! Code: ' + response.getStatusCode() + ', Status: ' + response.getStatus();
                    }
                }
            }
        }
        update shippingItems;
    }
    
    //Takes JSON and endpoint, returns the response
    public static HttpResponse apiCallout(String json, String endpoint){
        System.debug('JSON: ' + json);
        System.debug('ENDPOINT: ' + endpoint);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('x-api-key', '{!$Credential.Password}');
        req.setBody(json);
        Http http = new Http();
        HttpResponse response = http.send(req);
        return response;
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;    
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;    
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;    
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;    
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;    
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;        
    }    
}