force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Location Addresses with Accounts. Also links to Quotes.</description>
    <label>Account Address</label>
    <nameField>
        <label>Address Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Address1_1__c.field-meta.xml
<CustomField>
    <fullName>Address1_1__c</fullName>
    <formula>Location_Address__r.Address_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Address1_2__c.field-meta.xml
<CustomField>
    <fullName>Address1_2__c</fullName>
    <formula>Location_Address__r.Address_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Concatenates the address fields.</description>
    <formula>Address1_1__c + BR() + Address1_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Concatenates the address fields.</inlineHelpText>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/City1__c.field-meta.xml
<CustomField>
    <fullName>City1__c</fullName>
    <formula>Location_Address__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/Location_Address__c.object-meta.xml
<CustomObject>
    <description>Tracks the location addresses for clients, vendors and OSG. Global data set that can link to one or more Accounts.</description>
    <label>Location Address</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Concatenates the address fields.</description>
    <formula>Address_1__c +&quot; &quot;+  Address_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Concatenates the address fields.</inlineHelpText>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Captures the city of the location.</description>
    <inlineHelpText>Indicates the city of the location.</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Current_Inventory_Count__c.field-meta.xml
<CustomField>
    <fullName>Current_Inventory_Count__c</fullName>
    <description>Captures the current inventory count.</description>
    <inlineHelpText>Indicates the current inventory count.</inlineHelpText>
    <label>Current Inventory Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Distance_Learning__c.field-meta.xml
<CustomField>
    <fullName>Distance_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Captures the duration of the course in hours.</description>
    <inlineHelpText>Indicates the duration of the course in hours.</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/External_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Product_Name__c</fullName>
    <description>Captures the external product name to be used on quote output documents.</description>
    <inlineHelpText>Indicates the external product name to be used on quote output documents.</inlineHelpText>
    <label>External Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Physical_Good_Type__c.field-meta.xml
<CustomField>
    <fullName>Physical_Good_Type__c</fullName>
    <description>Captures the type of physical good of the Product.</description>
    <inlineHelpText>Indicates the type of physical good of the Product.</inlineHelpText>
    <label>Physical Good Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>DVD</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Recurring_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, will generate an automatic billing date on order products</inlineHelpText>
    <label>Recurring Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Recurring_Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Invoice_Frequency__c</fullName>
    <label>Recurring Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Recurring_Invoice_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <description>Captures the standard price displayed on the course.</description>
    <inlineHelpText>Indicates the standard price displayed on the course.</inlineHelpText>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Alternate_Contact__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the alternative contact for the service appointment.</description>
    <inlineHelpText>Indicates the alternative contact for the service appointment.</inlineHelpText>
    <label>Alternate Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Alternate contact must belong to account listed on SA!</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Confirmed_Seats__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Seats__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Captures the number Attendees on the Service Appointment where Confirmed = Yes.</description>
    <inlineHelpText>Indicates the Attendees on the Service Appointment where Confirmed = Yes.</inlineHelpText>
    <label>Confirmed Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Course_Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Course_Maximum_Capacity__c</fullName>
    <description>Captures the Product&apos;s Maximum Capacity (Maximum Attendees) for the training. Populated based on Product lookup indicated.</description>
    <inlineHelpText>Indicates the Product&apos;s Maximum Capacity (Maximum Attendees) for the training. Populated based on Product lookup indicated.</inlineHelpText>
    <label>DELETE_Course Maximum Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the course. Pulled from Product.</description>
    <inlineHelpText>Indicates the courses product line. Pulled from Product.</inlineHelpText>
    <label>Course Product Line</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Distance_Learning__c.field-meta.xml
<CustomField>
    <fullName>Distance_Learning__c</fullName>
    <formula>Product__r.Distance_Learning__c</formula>
    <label>Distance Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</description>
    <inlineHelpText>Indicates the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Spaces_Left__c.field-meta.xml
<CustomField>
    <fullName>Spaces_Left__c</fullName>
    <formula>Course_Max_Capacity__c - Confirmed_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spaces Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Training_Address1__c.field-meta.xml
<CustomField>
    <fullName>Training_Address1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Address</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account_Address__c.Location_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/F8_WebProductSelectionAPI.cls
/*********************************************************************************************************************
* F8_WebProductSelectionAPI class exposed as web-serivce
* Post- Create contact
* Author - Aditya Chasta
* Created date - 06/20/2017
**********************************************************************************************************************/

@RestResource(urlMapping='/Cart/ProductInfo/*')
global with sharing class F8_WebProductSelectionAPI {
    @HttpPost
    global static List<F8_WebResponseHandler> retrieveProduct(ProductInfoRequest requestProduct) {
        List<F8_WebProductSelectSuccessRespHandler> successResponseList = new List<F8_WebProductSelectSuccessRespHandler>(); //Object to store success response
        List<F8_WebErrorResponseHandler> errorResponseList = new List<F8_WebErrorResponseHandler>(); //Object to store error response
        F8_WebErrorResponseHandler errorResponse; 
        try {
            String whereStatement = 'where';
            String fromStatement = ') from Product2 ';
            //base query
            String query = 'select Id, Name, Distance_Learning__c, Recurring_Invoice__c, Recurring_Invoice_Frequency__c, Delivery_Method__c, External_Product_Name__c, SBQQ__DiscountSchedule__c, Train_The_Trainer__c, Family, Standard_Price__c, Duration__c, Physical_Good_Type__c, Course_Product_Line__c, Current_Inventory_Count__c, (select id, Street, City, State, PostalCode, SchedStartTime, SchedEndTime, Spaces_Left__c , Course_Maximum_Capacity__c,Training_Address1__c, Confirmed_Seats__c, Distance_Learning__c from Service_Appointments__r ';
            //It will be used to filter products
            String appointmentQuery = '(select Product__c from ServiceAppointment ';
            String serviceAppointmentString = 'id in ';
            String whereClauseForProduct = 'where IsActive = true and ((( Family = \'Courses\' and Delivery_Method__c = \'Classroom\' ) or Family = \'Physical Goods\') or (ProductCode = \'OL-TTAL\') or (ProductCode = \'OL-JHSCI\') or (ProductCode = \'OL-JHSCB\') or (ProductCode = \'CS-WSIB\')) and ( Course_Product_Line__c != \'SFACPR2\') and (Course_Product_Line__c != \'AI\') ';
            //if product has filter conditions

            String whereClauseForAppointment = '';// = whereStatement + ' (StatusCategory = \'Scheduled\' or StatusCategory = \'None\') ';
            //if service appointment has filter conditions
            Boolean whereForAppointment = false;
            
            /*Applying filters to appointment*/
            
            //If appointment_id is not null then include it in where clause
            if(String.isNotBlank(requestProduct.appointment_id)) {// if appointment_id is not null in the request
                whereClauseForAppointment = whereStatement+' id = '+'\''+requestProduct.appointment_id+'\' ';
                whereForAppointment = true;
            } 
            
            //If location is not null then include it in where clause
            if(String.isNotBlank(requestProduct.location)) {
                if(whereForAppointment) {
                    whereClauseForAppointment = whereClauseForAppointment + 'and City = '+'\''+String.escapeSingleQuotes(requestProduct.location)+'\' ';
                } else {
                    whereClauseForAppointment = whereStatement+' City = '+'\''+String.escapeSingleQuotes(requestProduct.location)+'\' ';
                    whereForAppointment = true;
                }
            }
                
            //If end_date is not null then include it in where clause
            if(String.isNotBlank(String.valueOf(requestProduct.end_date))) {
                //Converting the date string into date format
                //
                
            	Date endDate;
            
                if(String.isNotBlank(String.valueOf(requestProduct.end_date))) {
                	endDate = Date.valueOf(String.escapeSingleQuotes(requestProduct.end_date));
                } else {
                    endDate = Date.valueOf('2021-01-01');
                }
            
                //Converting the date into DateTime
                DateTime endDateTime = DateTime.newInstance(endDate.year(), endDate.month(),endDate.day());
                //Converting DateTime into YYYY-MM-DDTHH:MM:SSz format as query accepts only this format
                String endDateString = endDateTime.format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'');
                
                //Fetching today's date
                Date currentDate = Date.Today();
                //Converting the date into DateTime
                DateTime currentDateTime = DateTime.newInstance(currentDate.year(), currentDate.month(),currentDate.day());
                //Converting DateTime into YYYY-MM-DDTHH:MM:SSz format as query accepts only this format
                String currentDateString = currentDateTime.format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'');
                //endDateTime = endDateTime.format('yyyy-MM-dd\'T\'hh:mm:ss\'z\''); 
                if(whereForAppointment) {
                    whereClauseForAppointment = whereClauseForAppointment + 'and SchedStartTime >= ' + currentDateString + ' and SchedEndTime <= '+endDateString+' ';
                } else {
                    whereClauseForAppointment = whereStatement + ' SchedStartTime >= ' + currentDateString + ' and SchedEndTime <= '+endDateString+' ';
                    whereForAppointment = true;
                }
            }
            
            //Completing the filter query on ServiceAppointments
            if(whereForAppointment) {
                whereClauseForAppointment = whereClauseForAppointment + ' and (StatusCategory = \'Scheduled\' or StatusCategory = \'None\') ';
                 
                appointmentQuery = appointmentQuery + whereClauseForAppointment;
                query +=whereClauseForAppointment;
            }
            query += fromStatement;
            /*Applying filter on product*/
            
            //If product_id is not null the include it in the where clause
            if(String.isNotBlank(String.valueOf(requestProduct.product_id))) {
                whereClauseForProduct = whereClauseForProduct + 'and id = '+'\''+String.escapeSingleQuotes(requestProduct.product_id)+'\' ';
            }
            
            //If product_line is not null the include it in the where clause
            if(String.isNotBlank(String.valueOf(requestProduct.product_line))) {
                whereClauseForProduct = whereClauseForProduct + 'and Course_Product_Line__c = '+'\''+String.escapeSingleQuotes(requestProduct.product_line)+'\' ';
            }
            
            //If family is not null the include it in the where clause
            if(String.isNotBlank(String.valueOf(requestProduct.family))) {
                whereClauseForProduct = whereClauseForProduct + 'and Family = '+'\''+String.escapeSingleQuotes(requestProduct.family)+'\' ';
            }
                
            //Completing the query
            query = query + whereClauseForProduct;
            if(whereForAppointment) {
                query = query + 'and '+ serviceAppointmentString + appointmentQuery + ') ';
            }
        	
            query = query + 'LIMIT 50000';
            
            Map<Id, Id> appointAddressMap = new Map<Id, Id>();
            //System.assert(false,+'####'+query);
            //querying the products
            System.debug('QUERY: ' + query);
            List<Product2> productsToRetrieve = Database.query(query);
            
            if(productsToRetrieve != null && productsToRetrieve.size() != 0) { // If product list is not empty
                Set<Id> discScheIds = new Set<Id>();
                for(Product2 product : productsToRetrieve) {
                    if(Product.SBQQ__DiscountSchedule__c != null){
                        discScheIds.add(Product.SBQQ__DiscountSchedule__c);
                    }
                    
                    for(ServiceAppointment appointment : product.Service_Appointments__r) {
                        if(String.isNotBlank(appointment.Training_Address1__c)) {
                            appointAddressMap.put(appointment.id, appointment.Training_Address1__c);
                        }
                    }
                }
                Map<Id, Account_Address__c> accountAddressMap = new Map<Id, Account_Address__c>([select id,  Address1_1__c, Address1_2__c, City1__c, Province1__c, Postal_Code1__c, Web_Name__c, Province_State_Code__c from Account_Address__c where id in: appointAddressMap.values()]);
                Decimal remainingQuantity;
                
                //Map for Prodcut related Discount Tier
                Map<Id, List<SBQQ__DiscountTier__c>> mapDiscountTiers = new Map<Id, List<SBQQ__DiscountTier__c>>();
                if(discScheIds.size() > 0){
                    for(SBQQ__DiscountTier__c tier : [Select Id, SBQQ__Schedule__c, SBQQ__LowerBound__c, SBQQ__UpperBound__c, SBQQ__DiscountAmount__c From SBQQ__DiscountTier__c Where SBQQ__Schedule__c IN : discScheIds]){
                        if(!mapDiscountTiers.containsKey(tier.SBQQ__Schedule__c))
                            mapDiscountTiers.put(tier.SBQQ__Schedule__c, new List<SBQQ__DiscountTier__c>());
                        mapDiscountTiers.get(tier.SBQQ__Schedule__c).add(tier);
                    }
                
                }
                             //Iterating over all the products and setting response in related fields
                for(Product2 product : productsToRetrieve) {
                    System.debug('PROD: ' + product);
                    F8_WebProductSelectSuccessRespHandler successResponse = new F8_WebProductSelectSuccessRespHandler();
                    successResponse.id = product.id;
                    successResponse.name = product.External_Product_Name__c;
                    successResponse.product_line = product.Course_Product_Line__c;
                    successResponse.base_price = product.Standard_Price__c;
                    successResponse.duration = product.Duration__c;
                    successResponse.physical_good_type = product.Physical_Good_Type__c;
                    successResponse.train_the_trainer = product.Train_The_Trainer__c;
                    successResponse.distance_learning = product.Distance_Learning__c;
                    successResponse.delivery_method = product.Delivery_Method__c;
                    successResponse.recurring_invoice = product.Recurring_Invoice__c;
                    successResponse.recurring_invoice_frequency = product.Recurring_Invoice_Frequency__c;
                    
                    System.debug('SUCCRESP: ' + successResponse);
                    
                    if(mapDiscountTiers.containsKey(product.SBQQ__DiscountSchedule__c)){
                        for(SBQQ__DiscountTier__c tiers : mapDiscountTiers.get(product.SBQQ__DiscountSchedule__c)){
                            System.debug('TIER: ' + tiers);
                            //system.assert(false,'Price=='+product.Standard_Price__c+'---'+tiers.SBQQ__DiscountAmount__c+'----'+tiers.SBQQ__LowerBound__c +'-----'+tiers.SBQQ__UpperBound__c);
                            successResponse.pricing.add(new F8_WebProductSelectSuccessRespHandler.Pricing(tiers.SBQQ__LowerBound__c,tiers.SBQQ__UpperBound__c,(product.Standard_Price__c - tiers.SBQQ__DiscountAmount__c)));
                        }
                    }
                    
                    //Iterating over all the ServiceAppointments and setting response in related fields
                    for(ServiceAppointment appointment : product.Service_Appointments__r) {
                        System.debug('APPT: ' + appointment);
                        remainingQuantity = 0;
                        if(product.Family == 'Courses') {
                            /*if(appointment.Course_Maximum_Capacity__c != null && appointment.Confirmed_Seats__c != null) {
                                remainingQuantity = appointment.Course_Maximum_Capacity__c - appointment.Confirmed_Seats__c;
                            } else if(appointment.Course_Maximum_Capacity__c != null && (appointment.Confirmed_Seats__c == null || appointment.Confirmed_Seats__c == 0)) {
                                remainingQuantity = appointment.Course_Maximum_Capacity__c;
                            }*/
                            remainingQuantity = appointment.Spaces_Left__c ;
                        } else if (product.Family == 'Physical Goods') {
                            remainingQuantity = product.Current_Inventory_Count__c;
                        }
                        // Adding ServiceAppointment related response to appointments list
                        //Location_Address__c location_address = [select id,  Address__c, Address_2__c, City__c, Province__c,   Postal_Code__c from Location_Address__c where id =: appointment.Training_Address__c];
                        if(appointAddressMap.containsKey(appointment.id)){
                            Account_Address__c address = accountAddressMap.get(appointAddressMap.get(appointment.id));
                            System.debug('ADDR: ' + address);
                            if(address != null){
                            	successResponse.appointments.add(new F8_WebProductSelectSuccessRespHandler.Appointments(appointment.id, remainingQuantity, appointment.SchedStartTime, appointment.SchedEndTime, appointment.City, address.Address1_1__c, address.Address1_2__c,address.City1__c, address.Province1__c, address.Postal_Code1__c, address.Web_Name__c, address.Province_State_Code__c, appointment.Distance_Learning__c));
                            }
                            else{
                            	successResponse.appointments.add(new F8_WebProductSelectSuccessRespHandler.Appointments(appointment.id, remainingQuantity, appointment.SchedStartTime, appointment.SchedEndTime, appointment.City, appointment.Street,'', appointment.City, appointment.State, appointment.PostalCode, appointment.City, appointment.State, appointment.Distance_Learning__c));
                                
                            }
                        }
                        else {
                            successResponse.appointments.add(new F8_WebProductSelectSuccessRespHandler.Appointments(appointment.id, remainingQuantity, appointment.SchedStartTime, appointment.SchedEndTime, appointment.City, appointment.Street,'', appointment.City, appointment.State, appointment.PostalCode, appointment.City, appointment.State, appointment.Distance_Learning__c));
                    
                        }
                    }
                    successResponseList.add(successResponse);
                }
            }
            return successResponseList;
        } catch(Exception e) { // If some exception occurs
            //System.assert(false, 'ERROR : '+e.getMessage()+' Stack Trace : '+e.getStackTraceString());
            System.debug('EXC: ' + e);
            errorResponseList.add(F8_WebServices.generateErrorResponse('ERROR : '+e.getMessage()+' Stack Trace : '+e.getStackTraceString(), 'ERROR'));
        } 
        
        return errorResponseList;
    }
    
    /*
    * Wrapper class for request
    */
     global class ProductInfoRequest {
    
        global String product_id;
        global String appointment_id;
        global String location;
        global String end_date;
        global String family;
        global String product_line;
    }
    
    public static void doTest(){
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;        
    }
}