force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Location Addresses with Accounts. Also links to Quotes.</description>
    <label>Account Address</label>
    <nameField>
        <label>Address Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Location_Address__c</fullName>
    <description>Captures the relationship to the Location Address. Secondary relationship. Contains a lookup filter to the Location: Location Status = Active.</description>
    <inlineHelpText>Indicates the relationship to the Location Address. Secondary relationship. Filter to only display &quot;Active&quot; Location Addresses.</inlineHelpText>
    <label>Location Address</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No &quot;Active&quot; Location Addresses meets the search criteria. Please search for an alternate &quot;Active&quot; Location Address record or create a new one.</errorMessage>
        <filterItems>
            <field>Location_Address__c.Location_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select from &quot;Active&quot; Location Addresses.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location_Address__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Source Quote</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1STA</fullName>
            </value>
            <value>
                <fullName>1STA2</fullName>
            </value>
            <value>
                <fullName>1STAR</fullName>
            </value>
            <value>
                <fullName>2016OOHSAR</fullName>
            </value>
            <value>
                <fullName>2017OOHSAR</fullName>
            </value>
            <value>
                <fullName>2018OOHSAR</fullName>
            </value>
            <value>
                <fullName>2019OOHSAR</fullName>
            </value>
            <value>
                <fullName>2020OOHSAR</fullName>
            </value>
            <value>
                <fullName>2021OOHSAR</fullName>
            </value>
            <value>
                <fullName>2022OOHSAR</fullName>
            </value>
            <value>
                <fullName>2023OOHSAR</fullName>
            </value>
            <value>
                <fullName>3P</fullName>
            </value>
            <value>
                <fullName>4KSTEWI</fullName>
            </value>
            <value>
                <fullName>5LSAN4</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AEDP</fullName>
            </value>
            <value>
                <fullName>AEDT</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AHA</fullName>
            </value>
            <value>
                <fullName>AHATTT</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AIDAPRSS</fullName>
            </value>
            <value>
                <fullName>AIET</fullName>
            </value>
            <value>
                <fullName>AITTT</fullName>
            </value>
            <value>
                <fullName>AMME1</fullName>
            </value>
            <value>
                <fullName>AODA</fullName>
            </value>
            <value>
                <fullName>AODATTT</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASB</fullName>
            </value>
            <value>
                <fullName>JHSCI</fullName>
            </value>
            <value>
                <fullName>JHSCII</fullName>
            </value>
            <value>
                <fullName>TTAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the delivery method for the Product.</description>
    <inlineHelpText>Indicates the delivery method for the Product.</inlineHelpText>
    <label>Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>On-site</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Train-the-Trainer</fullName>
                <isActive>false</isActive>
                <label>Train-the-Trainer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Distance_Learning__c.field-meta.xml
<CustomField>
    <fullName>Distance_Learning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Classroom_Course__c.field-meta.xml
<CustomField>
    <fullName>Classroom_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</description>
    <inlineHelpText>Connection to scheduled &quot;Classroom&quot; Service Appointment records (IH or 3P). Establishes the ability to book seats (quoted quantity) against a classroom course.</inlineHelpText>
    <label>Classroom Course</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Classroom Quoted Seats</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the Product. Populated via Process Rule for use with roll-ups.</description>
    <inlineHelpText>Indicates the product line.</inlineHelpText>
    <label>Course Product Line</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Captures the Product&apos;s Delivery Method when applicable. Populated via Process Rule for use with roll-ups and Price Rules.</description>
    <inlineHelpText>Indicates the Product&apos;s Delivery Method when applicable.</inlineHelpText>
    <label>Delivery Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Captures the Product&apos;s Product Name. Used with roll-up summaries.</description>
    <inlineHelpText>Indicates the Product&apos;s Product Name. Used with roll-up summaries.</inlineHelpText>
    <label>RO Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Course_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Course_Product_Line__c</fullName>
    <description>Captures the product line for the course. Pulled from Product.</description>
    <inlineHelpText>Indicates the courses product line. Pulled from Product.</inlineHelpText>
    <label>Course Product Line</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Distance_Learning__c.field-meta.xml
<CustomField>
    <fullName>Distance_Learning__c</fullName>
    <formula>Product__r.Distance_Learning__c</formula>
    <label>Distance Learning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Captures the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</description>
    <inlineHelpText>Indicates the corresponding classroom, on-site, consulting service or evaluation Product record to pull down information into the Service Appointment (Course).</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Spaces_Left__c.field-meta.xml
<CustomField>
    <fullName>Spaces_Left__c</fullName>
    <formula>Course_Max_Capacity__c - Confirmed_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spaces Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Training_Address1__c.field-meta.xml
<CustomField>
    <fullName>Training_Address1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Address</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account_Address__c.Location_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Account_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClassroomCourseCmpApexController.cls
public with sharing class ClassroomCourseCmpApexController {
    
    @AuraEnabled(cacheable=true)
    public static List<QuoteLine> getValues(Id quoteId,String ProductFamily1,String ProductFamily2,String DeliveryMethod) {
        List<QuoteLine> QLIList= new List<QuoteLine>();
        for(SBQQ__QuoteLine__c QLI : [SELECT Name, SBQQ__Product__r.Name,SBQQ__Product__r.Id, SBQQ__Product__r.Distance_Learning__c, SBQQ__Quantity__c, Course_Product_Line__c, Classroom_Course__c,Classroom_Course__r.AppointmentNumber FROM SBQQ__QuoteLine__c
                                      where SBQQ__Quote__c =:quoteId AND (Delivery_Method__c =:DeliveryMethod OR Course_Product_Line__c = 'TTAL' OR Course_Product_Line__c = 'JHSCI') AND (SBQQ__ProductFamily__c=: ProductFamily1 OR SBQQ__ProductFamily__c=: ProductFamily2) and (SBQQ__RequiredBy__c = NULL or (Course_Product_Line__c = 'JHSCII' and SBQQ__RequiredBy__c != null))]){
            QuoteLine QL=new QuoteLine();
            QL.LineName = QLI.Name;
            QL.RecordId = QLI.Id;
            QL.ProductName = QLI.SBQQ__Product__r.Name;
            QL.ProductId = QLI.SBQQ__Product__r.Id;
            QL.Quantity = QLI.SBQQ__Quantity__c;
            QL.ClassroomName = QLI.Classroom_Course__r.AppointmentNumber;
            QL.CourseProductLine = QLI.Course_Product_Line__c;
			QL.apexDistanceLearning = QLI.SBQQ__Product__r.Distance_Learning__c;
            QLIList.add(QL);
            System.debug('Qli List'+QLIList);
        }
         return QLIList;
        }
    
//    @AuraEnabled
//     public static List<SBQQ__QuoteLine__c> findByName(String searchKey) {
//           String soqlStr = 'SELECT Name, SBQQ__Product__r.Name, SBQQ__Quantity__c, Classroom_Course__r.Id FROM SBQQ__QuoteLine__c WHERE name LIKE \'%' + searchKey + '%\'' ;
//         return database.query(soqlStr);
//     }

    @AuraEnabled
    public static List<ServiceAppointment> getClassroomValues(String courseprodLine,String ProdFamily1,String ProdFamily2,String DelMethod, Boolean DistanceLearning) {
        system.debug('cpLine--'+courseprodLine);
        system.debug('cpLine--'+ProdFamily1);
        system.debug('cpLine--'+ProdFamily2);
        system.debug('cpLine--'+DelMethod);
        system.debug('cpLine--'+DistanceLearning);
        System.debug('Query===>'+[SELECT AppointmentNumber, Training_Address1__r.Location_Address__r.Name, Spaces_Left__c, 
                                       Product_Name__c, IH3POS__c, Duration, SchedStartTime, SchedEndTime, 
                                       Course_Maximum_Capacity__c, Confirmed_Seats__c, Current_Quoted_Seats__c, Address 
                                       FROM ServiceAppointment WHERE (Course_Product_Line__c =: courseprodLine AND 
                                       Product__r.Delivery_Method__c =:DelMethod AND 
									   Distance_Learning__c = :DistanceLearning AND
                                       (Product_Family__c=: ProdFamily1 OR Product_Family__c=: ProdFamily2) AND 
                                       ( Status = 'Assigned' OR Status = 'Scheduled') AND SchedStartTime >= Today and Spaces_Left__c > 0)
                                       Order By SchedStartTime Asc]);
        List<ServiceAppointment> sa = [SELECT AppointmentNumber, Training_Address1__r.Location_Address__r.Name, Spaces_Left__c, 
                                       Product_Name__c, IH3POS__c, Duration, SchedStartTime, SchedEndTime, 
                                       Course_Maximum_Capacity__c, Confirmed_Seats__c, Current_Quoted_Seats__c, Address 
                                       FROM ServiceAppointment WHERE (Course_Product_Line__c =: courseprodLine AND 
                                       Product__r.Delivery_Method__c =:DelMethod AND 
									   Distance_Learning__c = :DistanceLearning AND
                                       (Product_Family__c=: ProdFamily1 OR Product_Family__c=: ProdFamily2) AND 
                                       ( Status = 'Assigned' OR Status = 'Scheduled') AND SchedStartTime >= Today and Spaces_Left__c > 0) 
                                       Order By SchedStartTime Asc];
         return sa;
    }
        
    // @AuraEnabled
    // public static List<ServiceAppointment> getUpdatesValues(String courseprodLine,String KeyStroke,String ProFamily1,String ProFamily2,String DeMethod, Boolean DistanceLearning) {
    //     KeyStroke='%'+KeyStroke+'%';
    //     List<ServiceAppointment> sa = [SELECT AppointmentNumber, Training_Address1__r.Name, Spaces_Left__c, Product_Name__c, 
    //                                    IH3POS__c, Duration, SchedStartTime, SchedEndTime, Course_Maximum_Capacity__c, Confirmed_Seats__c, 
    //                                    Current_Quoted_Seats__c, Address 
    //                                    FROM ServiceAppointment WHERE (Course_Product_Line__c =: courseprodLine AND
    //                                    Product__r.Delivery_Method__c =:DeMethod AND 
    //                                    Distance_Learning__c = :DistanceLearning AND 
    //                                    (Product_Family__c=: ProFamily1 OR Product_Family__c=: ProFamily2) AND 
    //                                    ( Status = 'Assigned' OR Status = 'Scheduled') AND SchedStartTime >= Today and Spaces_Left__c > 0) OR 
    //                                    (Product__r.Delivery_Method__c = 'Online' and Course_Product_Line__c =: courseprodLine)
    //                                    Order By SchedStartTime Asc];
    //      return sa;
    // }
    
    @AuraEnabled
    public static String SaveRecord(Id QuoteId,Id ServiceAppId) {
        
        SBQQ__QuoteLine__c sq= new SBQQ__QuoteLine__c(id=QuoteId,Classroom_Course__c=ServiceAppId);
        Update sq;
        ServiceAppointment src=[select id,AppointmentNumber from ServiceAppointment where id =: ServiceAppId];
        return src.AppointmentNumber ;
    }
    
    Public Class QuoteLine {
        @AuraEnabled
        public String LineName;
        @AuraEnabled
        public Id RecordId;
        @AuraEnabled
        public String ProductName;
        @AuraEnabled
        public Id ProductId;
        @AuraEnabled
        public Decimal Quantity;
        @AuraEnabled
        public String ClassroomName;
        @AuraEnabled
        public string CourseProductLine;
        @AuraEnabled
        public Boolean apexDistanceLearning;
    }
    
	public static void TestCodeCoverage() {
        Boolean CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;  
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false; 
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;
        CodeCoverage = true;
        CodeCoverage = false;        
    }    
    
}