force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Location Addresses with Accounts. Also links to Quotes.</description>
    <label>Account Address</label>
    <nameField>
        <label>Address Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Location_Address__c</fullName>
    <description>Captures the relationship to the Location Address. Secondary relationship. Contains a lookup filter to the Location: Location Status = Active.</description>
    <inlineHelpText>Indicates the relationship to the Location Address. Secondary relationship. Filter to only display &quot;Active&quot; Location Addresses.</inlineHelpText>
    <label>Location Address</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No &quot;Active&quot; Location Addresses meets the search criteria. Please search for an alternate &quot;Active&quot; Location Address record or create a new one.</errorMessage>
        <filterItems>
            <field>Location_Address__c.Location_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <infoMessage>Select from &quot;Active&quot; Location Addresses.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location_Address__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address__c/Location_Address__c.object-meta.xml
<CustomObject>
    <description>Tracks the location addresses for clients, vendors and OSG. Global data set that can link to one or more Accounts.</description>
    <label>Location Address</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address__c/fields/Location_Address__c.field-meta.xml
<CustomField>
    <fullName>Location_Address__c</fullName>
    <description>Concatenates the entire address fields.</description>
    <formula>Address__c + BR() + City__c + &quot; &quot;+ TEXT(Province__c) + BR() + Postal_Code__c + BR() + TEXT(Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Concatenates the entire address fields.</inlineHelpText>
    <label>Location Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Amazon_Sku__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Sku__c</fullName>
    <label>Amazon Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipLabel>Order Products (Shipping Address)</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Amazon_Sku__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Sku__c</fullName>
    <description>Holds any applicable amazon sku number</description>
    <label>Amazon Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/Shipping_Item__c.object-meta.xml
<CustomObject>
    <label>Shipping Item</label>
    <nameField>
        <label>Shipping Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Item__c/fields/Amazon_Sku__c.field-meta.xml
<CustomField>
    <fullName>Amazon_Sku__c</fullName>
    <label>Amazon Sku</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ship To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipped__c.field-meta.xml
<CustomField>
    <fullName>Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Account_Address__c</referenceTo>
    <relationshipName>Shipping_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Courrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Courrier__c</fullName>
    <label>Shipping Courrier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Canada Post</fullName>
            </value>
            <value>
                <fullName>Canpar</fullName>
            </value>
            <value>
                <fullName>Couriers Plus</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>FedEx</fullName>
            </value>
            <value>
                <fullName>Local Pickup</fullName>
            </value>
            <value>
                <fullName>OSS Supplier</fullName>
            </value>
            <value>
                <fullName>Purolator</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Item__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShippingItemTriggerHandlerTest.cls
@isTest
public class ShippingItemTriggerHandlerTest {
	
    @isTest(SeeAllData=true)
    //before insert, after insert, after update
    static void deployTrigger(){
        List<Product2> JHSCPosterProducts = [Select Amazon_Sku__c from Product2 where ProductCode = 'PG-JHSCP' and IsActive = TRUE and Amazon_Sku__c != NULL];
        List<String> JHSCPosterSKUs = new List<String>();
        for(Product2 product : JHSCPosterProducts){
            JHSCPosterSKUs.add(product.Amazon_Sku__c);
        }        
        
		Order order = [Select Id from Order Limit 1];
        OrderItem orderItem = [Select Id from OrderItem Limit 1];
        Product2 product = [Select Id from Product2 limit 1];
		Contact contact = [Select Id from Contact limit 1];
        Account_Address__c accountAddress = [Select Id from Account_Address__c where Location_Address__c != NULL limit 1];
        
		Shipping_Item__c shippingItem = (Shipping_Item__c) SmartFactory.createSObject('Shipping_Item__c');
        String testPosterSku = JHSCPosterSKUs[0];
        shippingItem.Order__c = order.Id;
        shippingItem.Order_Product__c = orderItem.Id;        
        shippingItem.Amazon_Sku__c = testPosterSku;
        shippingItem.Name = '1234-SHIPPING';
		shippingItem.Product__c = product.Id;
        shippingItem.Quantity__c = 1;
        shippingItem.Shipping_Method__c = 'Standard Courier';
        shippingItem.Shipping_Courrier__c = 'Amazon';
        shippingItem.Ship_To_Contact__c = contact.Id;
        shippingItem.Shipping_Address__c = accountAddress.Id;

        insert shippingItem;      
              
              
        Shipping_Item__c si3 = [Select Shipped__c from Shipping_Item__c where id = :shippingItem.Id];
        si3.Shipped__c = TRUE;
        update si3;
    }
    
    @isTest
    static void doTestCodeCoverage(){
        ShippingItemTriggerHandler.TestCodeCoverage();
    }  
}