force-app/main/default/objects/Contact/fields/unique_email__c.field-meta.xml
<CustomField>
    <fullName>unique_email__c</fullName>
    <label>Unique Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trigger_Setup__c/Trigger_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Allows for activation and deactivation of Apex Triggers.</description>
    <label>Trigger Setup</label>
</CustomObject>

force-app/main/default/objects/Trigger_Setup__c/fields/Deactivate_ContactTrigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_ContactTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows for deactivation of all Contact Trigger when checked.</description>
    <inlineHelpText>Allows for deactivation of all Contact Trigger when checked.</inlineHelpText>
    <label>Deactivate ContactTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SetContactUniqueEmailMD5Test.cls
@isTest(SeeAllData=true)
private class SetContactUniqueEmailMD5Test {
    @isTest
    static void updateContact(){
        Trigger_Setup__c triggSetting = Trigger_Setup__c.getInstance('Trigger Setup');
        triggSetting.Deactivate_ContactTrigger__c = true;
        update triggSetting;
        
        Contact c = [select id from Contact where unique_email__c = 'greg@osg.ca' limit 1];
        c.email = 'x_greg@osg.ca';
        c.unique_email__c = 'x_greg@osg.ca';
        update c;
    }    
    
}